/** TEXT dictionary — copied verbatim from "KIS Inventory & Counts.dc.html" (+ a few keys for strings the prototype kept as data). */
const EN = {
  title: 'Inventory & Counts',
  ledger: 'Ledger', setup: 'Count setup', review: 'Count review', stockValue: 'Stock value', movesToday: 'Movements today',
  lowStock: 'Low-stock items', openVariances: 'Open variances', searchPh: 'Search product…', today: 'Today',
  time: 'Time', product: 'Product', movement: 'Movement', location: 'Location', qtyChange: 'Qty change', onHand: 'On-hand',
  valueImpact: 'Value', source: 'Source', beyondTol: 'Beyond tol.', emptyLedger: 'No movements in this range.',
  all: 'All', belowMin: 'Below min', onHandNow: 'On-hand', avgCost: 'Avg cost / base', minMax: 'Min / Max',
  stockStatement: 'Stock-card statement', thisWeek: 'This week', variance: 'Variance (expected vs physical)',
  favorable: 'Favorable', withinTol: 'Within tolerance', unfavorable: 'Unfavorable',
  adjustStock: 'Adjust stock', startCount: 'Start count for this item', export: 'Export',
  onHandTrend: 'On-hand · last 14 days', daysAgo: '14 d ago', minLine: 'min level', recentMoves: 'Recent movements',
  setupHint: 'Frequency and critical flag are set per item per location.',
  startCountAll: 'Start count — all locations', startCountOne: 'Start count', item: 'Item', critical: 'Critical',
  countUnitLbl: 'count unit', setupNote: 'Launching all-locations creates parallel count tasks per location. Every config change is audit-logged.',
  totalFavorable: 'Total favorable', totalUnfavorable: 'Total unfavorable', netVariance: 'Net variance', countAccuracy: 'Count accuracy',
  reviewHint: 'Sorted by absolute cost impact — biggest problems on top. Staff never saw expected numbers.',
  expected: 'Expected', physical: 'Physical', qtyVariance: 'Qty variance', costImpact: 'Cost impact', status: 'Status',
  accept: 'Accept', accepted: 'Accepted ✓', recount: 'Recount', emptyReview: 'No count variances for this scope.',
  cancel: 'Cancel',
  adjustTitle: 'Adjust stock', adjustBody: 'Adjustments are approval-gated and audit-logged. Enter the reason for this adjustment.',
  adjustPh: 'e.g. Spillage during storage transfer', adjustWarn: 'This will create an adjustment movement — the original movements remain immutable.', adjustCta: 'Approve adjustment',
  acceptTitle: 'Accept variance', acceptBody: 'Accepting writes off the variance at moving-average cost. This requires approval and is logged.',
  acceptWarn: 'The variance amount will post to this location’s P&L as a stock write-off.', acceptCta: 'Accept & log',
  startAllTitle: 'Start count — all locations', startAllBody: 'Creates three parallel count tasks (Main Kitchen, Rock, Kaddoum) using each item’s per-location frequency and count unit. Staff see no expected quantities.',
  startWarn: 'Counters will be assigned per location. Progress is visible in Count review as tasks submit.', startCta: 'Launch count',
  startOneTitle: 'Start count', countLaunched: 'Count launched — 3 parallel location tasks created', countLaunchedOne: 'Count launched for', adjustSent: 'Adjustment approved & logged',
  acceptedToast: 'Variance accepted — posted to P&L', recountToast: 'Recount task created',
  types: { rcv: 'Received', prodIn: 'Production in', prodOut: 'Production out', trfOut: 'Transfer out', trfIn: 'Transfer in', waste: 'Waste', sale: 'Sale consumption', adj: 'Adjustment', count: 'Count' },
  freqs: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', adhoc: 'Ad-hoc' },
  locs: { mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' },
  // ── strings the prototype kept inline / as data ──
  chipProd: 'Production', chipTrf: 'Transfers', baseWord: 'base', counted: 'counted', recipeConsumption: 'recipe consumption',
  stmt: { opening: 'Opening', received: 'Received', prodIn: 'Production in', used: 'Used in production', sold: 'Sold (recipe)', waste: 'Waste', transfers: 'Transfers', adjustments: 'Adjustments', expected: 'Expected closing', physical: 'Physical count' },
  adjustQtyPh: 'Qty change in base unit, e.g. −2', recountPending: 'Recount pending', exportToast: 'Export queued — stock-card.xlsx',
  rawMaterial: 'Raw material', subRecipe: 'Sub-recipe', prepared: 'Prepared', menuItem: 'Menu item', packaging: 'Packaging',
};

export type InvText = typeof EN;

export const TEXT: Record<'en' | 'ar', InvText> = {
  en: EN,
  ar: {
    title: 'المخزون والجرد',
    ledger: 'السجل', setup: 'إعداد الجرد', review: 'مراجعة الجرد', stockValue: 'قيمة المخزون', movesToday: 'حركات اليوم',
    lowStock: 'أصناف منخفضة', openVariances: 'فروقات مفتوحة', searchPh: 'ابحث عن صنف…', today: 'اليوم',
    time: 'الوقت', product: 'الصنف', movement: 'الحركة', location: 'الموقع', qtyChange: 'تغير الكمية', onHand: 'الرصيد',
    valueImpact: 'القيمة', source: 'المصدر', beyondTol: 'خارج الحد', emptyLedger: 'لا حركات في هذه الفترة.',
    all: 'الكل', belowMin: 'تحت الأدنى', onHandNow: 'الرصيد الحالي', avgCost: 'متوسط الكلفة / الأساس', minMax: 'الأدنى / الأقصى',
    stockStatement: 'كشف بطاقة المخزون', thisWeek: 'هذا الأسبوع', variance: 'الفرق (المتوقع مقابل الفعلي)',
    favorable: 'إيجابي', withinTol: 'ضمن الحد', unfavorable: 'سلبي',
    adjustStock: 'تسوية المخزون', startCount: 'بدء جرد لهذا الصنف', export: 'تصدير',
    onHandTrend: 'الرصيد · آخر ١٤ يوماً', daysAgo: 'قبل ١٤ ي', minLine: 'الحد الأدنى', recentMoves: 'الحركات الأخيرة',
    setupHint: 'التواتر وعلامة الحرج يُحددان لكل صنف في كل موقع.',
    startCountAll: 'بدء جرد — كل المواقع', startCountOne: 'بدء جرد', item: 'الصنف', critical: 'حرج',
    countUnitLbl: 'وحدة العد', setupNote: 'إطلاق جرد كل المواقع ينشئ مهام جرد متوازية لكل موقع. كل تغيير في الإعداد يُسجل في سجل التدقيق.',
    totalFavorable: 'إجمالي الإيجابي', totalUnfavorable: 'إجمالي السلبي', netVariance: 'صافي الفرق', countAccuracy: 'دقة الجرد',
    reviewHint: 'مرتبة حسب الأثر المطلق على الكلفة — أكبر المشاكل أولاً. الموظفون لم يروا الأرقام المتوقعة.',
    expected: 'المتوقع', physical: 'الفعلي', qtyVariance: 'فرق الكمية', costImpact: 'أثر الكلفة', status: 'الحالة',
    accept: 'قبول', accepted: 'مقبول ✓', recount: 'إعادة جرد', emptyReview: 'لا فروقات جرد لهذا النطاق.',
    cancel: 'إلغاء',
    adjustTitle: 'تسوية المخزون', adjustBody: 'التسويات تتطلب موافقة وتُسجل في سجل التدقيق. أدخل سبب هذه التسوية.',
    adjustPh: 'مثال: انسكاب أثناء نقل التخزين', adjustWarn: 'سيُنشئ هذا حركة تسوية — الحركات الأصلية تبقى غير قابلة للتعديل.', adjustCta: 'اعتماد التسوية',
    acceptTitle: 'قبول الفرق', acceptBody: 'القبول يشطب الفرق بمتوسط الكلفة المتحرك. يتطلب موافقة ويُسجل.',
    acceptWarn: 'سيُرحّل مبلغ الفرق إلى قائمة أرباح وخسائر هذا الموقع كشطب مخزون.', acceptCta: 'قبول وتسجيل',
    startAllTitle: 'بدء جرد — كل المواقع', startAllBody: 'ينشئ ثلاث مهام جرد متوازية (المطبخ الرئيسي، روك، قدّوم) باستخدام تواتر ووحدة عد كل صنف في كل موقع. الموظفون لا يرون الكميات المتوقعة.',
    startWarn: 'سيُعيّن العدّادون لكل موقع. يظهر التقدم في مراجعة الجرد فور تسليم المهام.', startCta: 'إطلاق الجرد',
    startOneTitle: 'بدء جرد', countLaunched: 'أُطلق الجرد — ٣ مهام مواقع متوازية', countLaunchedOne: 'أُطلق الجرد في', adjustSent: 'اعتُمدت التسوية وسُجّلت',
    acceptedToast: 'قُبل الفرق — رُحّل إلى الأرباح والخسائر', recountToast: 'أُنشئت مهمة إعادة جرد',
    types: { rcv: 'استلام', prodIn: 'إنتاج داخل', prodOut: 'إنتاج خارج', trfOut: 'تحويل صادر', trfIn: 'تحويل وارد', waste: 'هدر', sale: 'استهلاك مبيعات', adj: 'تسوية', count: 'جرد' },
    freqs: { daily: 'يومي', weekly: 'أسبوعي', monthly: 'شهري', adhoc: 'عند الحاجة' },
    locs: { mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' },
    chipProd: 'إنتاج', chipTrf: 'تحويلات', baseWord: 'أساس', counted: 'معدود', recipeConsumption: 'استهلاك وصفات',
    stmt: { opening: 'الافتتاحي', received: 'استلام', prodIn: 'إنتاج داخل', used: 'استخدام في الإنتاج', sold: 'مبيع عبر الوصفات', waste: 'هدر', transfers: 'تحويلات', adjustments: 'تسويات', expected: 'الإقفال المتوقع', physical: 'الجرد الفعلي' },
    adjustQtyPh: 'تغير الكمية بوحدة الأساس، مثال: −2', recountPending: 'إعادة جرد معلّقة', exportToast: 'وُضع التصدير في الطابور — stock-card.xlsx',
    rawMaterial: 'مادة خام', subRecipe: 'وصفة فرعية', prepared: 'مُحضّر', menuItem: 'صنف قائمة', packaging: 'تغليف',
  },
};
