/** MGT-PRD-06 — TEXT dictionary (prototype strings verbatim + keys needed for product-aware labels). */
const EN = {
  title: 'Production gap review', period: 'Aug 2026 · Main Kitchen', periodShort: 'Aug 2026',
  avgGap: 'Avg gap — taouk', avgGapPrefix: 'Avg gap', vsStandard: 'vs 100 g/skewer standard', vsStandardGeneric: 'vs recipe standard', costImpact: 'Cost impact', thisPeriod: 'this period',
  openGaps: 'Open gaps', awaitingAccept: 'awaiting review', verdictTitle: 'Pattern',
  batch: 'Batch', standard: 'Recipe std', actual: 'Actual used', stdVsAct: 'Actual vs std', gap: 'Gap (w · % · $)', marinade: 'Marinade var',
  stdShort: 'std', marShort: 'mar.', employee: 'Employee', status: 'Status', accept: 'Accept', flag: 'Flag',
  acceptedPill: 'Accepted ✓', flaggedPill: 'Flagged',
  tableNote: 'Leftover returns are already resolved into "actual used" — only real portioning variance shows here. Accepting is kitchen-manager confirmation, logged.',
  trendTitle: 'Gap trend — taouk skewers', trendPrefix: 'Gap trend', trendSub: 'weekly avg, 8 weeks',
  trendVerdict: 'Consistent +8–11% for 6 weeks across 3 employees — this looks like the standard, not the people.',
  withinTol: 'Within tolerance — no concerning pattern.',
  aboveTol: 'Above tolerance — review the flagged batches below.',
  decisionTitle: 'Recipe vs process', decisionBody: 'A persistent gap means either the 100 g/skewer standard is unrealistic (recipe problem) or cutting drifts above 20–22 g (process problem). History across employees is the tiebreaker.',
  suggestCta: 'Open recipe-change suggestion → B3',
  feedNote: 'Accepted gaps post to cost (B7) and P&L (B8). Every accept/flag is audit-logged (E4).',
  acceptTitle: 'Accept gap', acceptBody: 'Confirms the variance as reviewed; the cost impact stays in this period’s numbers. Logged with your name.',
  acceptWarn: 'Accepting does not adjust stock — production already consumed at actual. This is the review sign-off.',
  acceptCtaM: 'Accept & log', flagTitle: 'Flag for action', flagBody: 'Creates a corrective action (E6/compliance) assigned to the shift lead — e.g. re-brief the 20–22 g cutting spec.',
  flagWarn: 'The batch stays open until the action closes.', flagCtaM: 'Flag & assign',
  suggestTitle: 'Recipe-change suggestion', suggestBody: 'Drafts a B3 suggestion: raise the taouk skewer standard from 100 g to a history-based value (~108 g), pending recipe-owner approval and versioning.',
  suggestPh: 'Note to the recipe owner…', suggestWarn: 'If approved, B3 creates a new recipe version (reason required) — history is never restated.',
  suggestCtaM: 'Send suggestion',
  acceptToast: 'Accepted — logged, posted to cost', flagToast: 'Flagged — corrective action created', suggestToast: 'Suggestion sent to B3 — pending approval',
  cancel: 'Cancel',
  products: { taouk: 'Taouk skewers', patties: 'Beef patties', toum: 'Toum', all: 'All products' } as Record<string, string>,
  noRows: 'No reconciled batches for this product in scope.',
  flagAlert: (id: string) => `Batch ${id} flagged for corrective action — cutting spec re-brief`,
};

export type Text = typeof EN;

export const TEXT: Record<'en' | 'ar', Text> = {
  en: EN,
  ar: {
    title: 'مراجعة فجوات الإنتاج', period: 'آب ٢٠٢٦ · المطبخ الرئيسي', periodShort: 'آب ٢٠٢٦',
    avgGap: 'متوسط الفجوة — طاووق', avgGapPrefix: 'متوسط الفجوة', vsStandard: 'مقابل معيار ١٠٠ غ/سيخ', vsStandardGeneric: 'مقابل معيار الوصفة', costImpact: 'أثر الكلفة', thisPeriod: 'هذه الفترة',
    openGaps: 'فجوات مفتوحة', awaitingAccept: 'بانتظار المراجعة', verdictTitle: 'النمط',
    batch: 'الدفعة', standard: 'معيار الوصفة', actual: 'المستخدم فعلاً', stdVsAct: 'الفعلي مقابل المعيار', gap: 'الفجوة (وزن · ٪ · $)', marinade: 'فرق التتبيلة',
    stdShort: 'المعيار', marShort: 'تتبيلة', employee: 'الموظف', status: 'الحالة', accept: 'قبول', flag: 'تبليغ',
    acceptedPill: 'مقبولة ✓', flaggedPill: 'مُبلّغة',
    tableNote: 'إرجاعات المتبقي محسومة مسبقاً في «المستخدم فعلاً» — لا يظهر هنا إلا فرق التقطيع الحقيقي. القبول تأكيد مدير المطبخ، ويُسجل.',
    trendTitle: 'اتجاه الفجوة — أسياخ الطاووق', trendPrefix: 'اتجاه الفجوة', trendSub: 'متوسط أسبوعي، ٨ أسابيع',
    trendVerdict: '+٨–١١٪ ثابتة لستة أسابيع عبر ٣ موظفين — يبدو أنها مشكلة المعيار لا الأشخاص.',
    withinTol: 'ضمن الحد — لا نمط مقلق.',
    aboveTol: 'فوق الحد — راجع الدفعات المميّزة أدناه.',
    decisionTitle: 'وصفة أم عملية', decisionBody: 'الفجوة المستمرة تعني إما أن معيار ١٠٠ غ/سيخ غير واقعي (مشكلة وصفة) أو أن التقطيع ينحرف فوق ٢٠–٢٢ غ (مشكلة عملية). التاريخ عبر الموظفين هو الحكم.',
    suggestCta: 'فتح اقتراح تعديل الوصفة ← B3',
    feedNote: 'الفجوات المقبولة تُرحّل إلى الكلفة (B7) والأرباح والخسائر (B8). كل قبول/تبليغ يُسجل بالتدقيق (E4).',
    acceptTitle: 'قبول الفجوة', acceptBody: 'يؤكد الفرق كمُراجَع؛ يبقى أثر الكلفة في أرقام الفترة. يُسجل باسمك.',
    acceptWarn: 'القبول لا يعدّل المخزون — الإنتاج استهلك فعلياً. هذا توقيع المراجعة.',
    acceptCtaM: 'قبول وتسجيل', flagTitle: 'تبليغ للإجراء', flagBody: 'ينشئ إجراءً تصحيحياً (الالتزام) مسنداً لمسؤول الوردية — مثل إعادة شرح معيار التقطيع ٢٠–٢٢ غ.',
    flagWarn: 'تبقى الدفعة مفتوحة حتى إغلاق الإجراء.', flagCtaM: 'تبليغ وإسناد',
    suggestTitle: 'اقتراح تعديل الوصفة', suggestBody: 'يصيغ اقتراحاً في B3: رفع معيار سيخ الطاووق من ١٠٠ غ إلى قيمة مبنية على التاريخ (~١٠٨ غ)، بانتظار موافقة مالك الوصفة والإصدار.',
    suggestPh: 'ملاحظة لمالك الوصفة…', suggestWarn: 'عند الموافقة ينشئ B3 إصداراً جديداً (السبب إلزامي) — التاريخ لا يُعاد أبداً.',
    suggestCtaM: 'إرسال الاقتراح',
    acceptToast: 'قُبلت — سُجلت ورُحّلت للكلفة', flagToast: 'بُلّغت — أُنشئ إجراء تصحيحي', suggestToast: 'أُرسل الاقتراح إلى B3 — بانتظار الموافقة',
    cancel: 'إلغاء',
    products: { taouk: 'أسياخ طاووق', patties: 'أقراص لحم', toum: 'ثوم مدقوق', all: 'كل المنتجات' },
    noRows: 'لا دفعات مطابَقة لهذا المنتج ضمن النطاق.',
    flagAlert: (id: string) => `الدفعة ${id} مُبلّغة لإجراء تصحيحي — إعادة شرح معيار التقطيع`,
  },
};
