/** Purchasing (MGT-PUR-01 / PUR-INV-01 / PUR-SUP-01). EN/AR copied verbatim from the prototype, plus keys for the store-backed PO chain. */
export const TEXT = {
  en: {
    title: 'Purchasing', userName: 'Rami Haddad', userRole: 'Purchasing · Cost control',
    tabOrders: 'Received suppliers', tabInvoice: 'Invoice review', tabSuppliers: 'Suppliers',
    newOrder: 'New order request', supplier: 'Supplier', searchSup: 'Search suppliers…', addItems: 'Add items', searchItems: 'Search items…', pickItems: 'Pick items to add to the order.',
    item: 'Item', qty: 'Qty', estPrice: 'Est. price', estTotal: 'Est. total', cancel: 'Cancel', sendOrder: 'Send to supplier', whatsapp: 'WhatsApp', email: 'Email',
    receiverNoteLabel: 'Note for receiver', receiverNotePh: 'e.g. Check expiry dates · weigh each box · call me on arrival…', receiverNoteHint: 'Shown to the receiver on the tablet when this delivery arrives.', seenOnTablet: 'seen on tablet',
    ordersFoot: 'An order request is sent to the supplier. On arrival it is logged in Receiving, then its invoice flows to the review pipeline.',
    viewInvoice: 'View invoice in pipeline', requested: 'Requested', sent: 'Sent', received: 'Received', invoiced: 'Invoiced',
    newSupplier: 'New supplier', orderFrom: 'Order from', contact: 'Contact', terms: 'Payment terms', spend30: 'Spend · 30d', spend: 'Spend', outstanding: 'Outstanding',
    nsName: 'Supplier name', nsNamePh: 'e.g. Cedar Meats', nsCat: 'Category', nsCatPh: 'e.g. Butchery', nsTermsPh: 'e.g. Net 30', nsContactPh: 'Contact person', nsPhone: 'Phone', saveSup: 'Save supplier', nsHint: 'Products and price history build up automatically as this supplier’s invoices flow through the review pipeline.', noHistory: 'No price history yet.',
    addProduct: 'Add product', apNamePh: 'e.g. Chicken wings', saveProduct: 'Save product', noProducts: 'No products yet — add the items this supplier delivers.',
    prodSupplied: 'From invoices', prodCatalog: 'Catalog', suppliedHint: 'Items seen on this supplier’s invoices — built automatically from the review pipeline.', catalogHint: 'Items you add manually to this supplier’s catalog for ordering.', noSupplied: 'No invoiced items yet — they appear here once an invoice is approved.', noCatalog: 'No catalog items yet — tap “Add product” to add what this supplier delivers.',
    noteTag: 'Note', src: '', scannedInvoice: 'Scanned invoice', attachedByReceiver: 'attached by receiver', noScanTitle: 'No scan attached', noScanBody: 'Receiver submitted with issue — enter manually in the pipeline.',
    receiverNoteFlag: 'Note from receiver', recDetail: 'The receiver logged this delivery. Open it in the review pipeline to enter and verify the invoice lines, prices and tax before posting.', reviewInPipeline: 'Review invoice in pipeline', pendingReview: 'Pending review', reviewed: 'Reviewed', scannedTag: 'Scanned', manualTag: 'Manual',
    p30: '30d', p90: '90d', p12m: '12m', pAll: 'All', spendLast: 'last', spendFrom: 'from', untilToday: 'until today', days: 'days', invoices: 'invoices',
    productsSupplied: 'Products supplied', product: 'Product', unit: 'Unit', lastPrice: 'Last price', avgPrice: 'Avg price', trend90: '90-day trend', lastDelivery: 'Last delivery',
    invoiceHistory: 'Invoice history', fromPipeline: 'from review pipeline', colInvNo: 'Invoice', colDate: 'Date', colValue: 'Value', colVat: 'VAT', status: 'Status', paid: 'Paid', due: 'Due', unpaidOnly: 'Unpaid only', noInvoices: 'No invoices.', noUnpaid: 'No unpaid invoices.', filterHint: 'Tap to see unpaid', clearFilterHint: 'Showing unpaid · tap to clear',
    priceHistory: 'Price history', today: 'today',
    orderToast: 'Order request sent to supplier', invToast: 'Opening invoice in review pipeline (PUR-INV-01)', newSupToast: 'New supplier form — demo', poInvoiceToast: 'Opening linked invoice (PUR-INV-01)',
    items: 'items', dueLine: 'due ', orderRequestTo: 'Order request to ', note: 'Note: ', orderRequest: 'Order request',
    // ported additions — store-backed purchase orders
    tabPo: 'Order requests', noOrders: 'No order requests in this scope.', noReceived: 'No receiver submissions in this scope.',
    cancelled: 'Cancelled', partial: 'Partially received', location: 'Location', expected: 'Expected', createdBy: 'Created by', lines: 'Lines', total: 'Total', recv: 'recv',
    saveDraft: 'Save as draft', draftToast: 'Order request saved as draft', editOrder: 'Edit', cancelOrder: 'Cancel order', cancelQ: 'Cancel this order request?', cancelBody: 'The supplier will not be expecting this delivery. The request stays in the audit trail.', cancelCta: 'Cancel request', cancelToast: 'Order request cancelled',
    logOnTablet: 'Log delivery on tablet', delivery: 'Delivery', addProductToast: 'Product added to catalog', newSupplierSaved: 'Supplier saved',
    addItemPre: 'Add “', addItemPost: '”',
  },
  ar: {
    title: 'المشتريات', userName: 'رامي حداد', userRole: 'المشتريات · مراقبة التكاليف',
    tabOrders: 'الموردون المستلمون', tabInvoice: 'مراجعة الفواتير', tabSuppliers: 'الموردون',
    newOrder: 'طلب شراء جديد', supplier: 'المورد', searchSup: 'ابحث عن مورد…', addItems: 'إضافة أصناف', searchItems: 'ابحث عن صنف…', pickItems: 'اختر أصنافاً لإضافتها إلى الطلب.',
    item: 'الصنف', qty: 'الكمية', estPrice: 'السعر التقديري', estTotal: 'الإجمالي التقديري', cancel: 'إلغاء', sendOrder: 'إرسال إلى المورد', whatsapp: 'واتساب', email: 'بريد',
    receiverNoteLabel: 'ملاحظة للمستلِم', receiverNotePh: 'مثال: تحقق من تواريخ الصلاحية · زن كل صندوق · اتصل بي عند الوصول…', receiverNoteHint: 'تُعرض للمستلِم على الجهاز اللوحي عند وصول التوريد.', seenOnTablet: 'تُرى على الجهاز اللوحي',
    ordersFoot: 'يُرسل طلب الشراء إلى المورد. عند الوصول يُسجّل في الاستلام، ثم تنتقل فاتورته إلى خط المراجعة.',
    viewInvoice: 'عرض الفاتورة في الخط', requested: 'مطلوب', sent: 'مُرسل', received: 'مُستلم', invoiced: 'مُفوتر',
    newSupplier: 'مورد جديد', orderFrom: 'اطلب من', contact: 'جهة الاتصال', terms: 'شروط الدفع', spend30: 'الإنفاق · ٣٠ يوماً', spend: 'الإنفاق', outstanding: 'المستحق',
    nsName: 'اسم المورد', nsNamePh: 'مثال: لحوم الأرز', nsCat: 'الفئة', nsCatPh: 'مثال: ملحمة', nsTermsPh: 'مثال: ٣٠ يوم', nsContactPh: 'الشخص المسؤول', nsPhone: 'الهاتف', saveSup: 'حفظ المورد', nsHint: 'تتكوّن الأصناف وتاريخ الأسعار تلقائياً مع مرور فواتير المورد في خط المراجعة.', noHistory: 'لا تاريخ أسعار بعد.',
    addProduct: 'إضافة صنف', apNamePh: 'مثال: أجنحة دجاج', saveProduct: 'حفظ الصنف', noProducts: 'لا أصناف بعد — أضف الأصناف التي يوردها هذا المورد.',
    prodSupplied: 'من الفواتير', prodCatalog: 'الكتالوج', suppliedHint: 'أصناف ظهرت على فواتير هذا المورد — تُبنى تلقائياً من خط المراجعة.', catalogHint: 'أصناف تضيفها يدوياً إلى كتالوج هذا المورد للطلب.', noSupplied: 'لا أصناف مفوترة بعد — تظهر هنا بعد اعتماد فاتورة.', noCatalog: 'لا أصناف في الكتالوج — اضغط «إضافة صنف».',
    noteTag: 'ملاحظة', src: '', scannedInvoice: 'الفاتورة الممسوحة', attachedByReceiver: 'أرفقها المستلِم', noScanTitle: 'لا مسح مرفق', noScanBody: 'أرسل المستلِم مع ملاحظة — أدخلها يدوياً في الخط.',
    receiverNoteFlag: 'ملاحظة من المستلِم', recDetail: 'سجّل المستلِم هذا التوريد. افتحه في خط المراجعة لإدخال أسطر الفاتورة والأسعار والضريبة والتحقق منها قبل الترحيل.', reviewInPipeline: 'مراجعة الفاتورة في الخط', pendingReview: 'بانتظار المراجعة', reviewed: 'روجعت', scannedTag: 'ممسوحة', manualTag: 'يدوي',
    p30: '٣٠ي', p90: '٩٠ي', p12m: '١٢ش', pAll: 'الكل', spendLast: 'آخر', spendFrom: 'من', untilToday: 'حتى اليوم', days: 'يوماً', invoices: 'فواتير',
    productsSupplied: 'الأصناف الموردة', product: 'الصنف', unit: 'الوحدة', lastPrice: 'آخر سعر', avgPrice: 'متوسط السعر', trend90: 'اتجاه ٩٠ يوماً', lastDelivery: 'آخر تسليم',
    invoiceHistory: 'سجل الفواتير', fromPipeline: 'من خط المراجعة', colInvNo: 'الفاتورة', colDate: 'التاريخ', colValue: 'القيمة', colVat: 'الضريبة', status: 'الحالة', paid: 'مدفوعة', due: 'مستحقة', unpaidOnly: 'غير المدفوعة فقط', noInvoices: 'لا فواتير.', noUnpaid: 'لا فواتير غير مدفوعة.', filterHint: 'اضغط لعرض غير المدفوعة', clearFilterHint: 'يُعرض غير المدفوع · اضغط للمسح',
    priceHistory: 'تاريخ الأسعار', today: 'اليوم',
    orderToast: 'أُرسل طلب الشراء إلى المورد', invToast: 'فتح الفاتورة في خط المراجعة (PUR-INV-01)', newSupToast: 'نموذج مورد جديد — تجريبي', poInvoiceToast: 'فتح الفاتورة المرتبطة (PUR-INV-01)',
    items: 'أصناف', dueLine: 'الاستحقاق ', orderRequestTo: 'طلب توريد إلى ', note: 'ملاحظة: ', orderRequest: 'طلب توريد',
    tabPo: 'طلبات الشراء', noOrders: 'لا طلبات شراء في هذا النطاق.', noReceived: 'لا تسليمات مسجلة في هذا النطاق.',
    cancelled: 'ملغى', partial: 'مُستلم جزئياً', location: 'الموقع', expected: 'متوقع', createdBy: 'أنشأه', lines: 'الأسطر', total: 'الإجمالي', recv: 'مستلم',
    saveDraft: 'حفظ كمسودة', draftToast: 'حُفظ طلب الشراء كمسودة', editOrder: 'تعديل', cancelOrder: 'إلغاء الطلب', cancelQ: 'إلغاء طلب الشراء هذا؟', cancelBody: 'لن يتوقع المورد هذا التوريد. يبقى الطلب في سجل التدقيق.', cancelCta: 'إلغاء الطلب', cancelToast: 'أُلغي طلب الشراء',
    logOnTablet: 'تسجيل التوريد على الجهاز اللوحي', delivery: 'التسليم', addProductToast: 'أُضيف الصنف إلى الكتالوج', newSupplierSaved: 'حُفظ المورد',
    addItemPre: 'إضافة “', addItemPost: '”',
  },
} as const;

export type PurText = typeof TEXT['en'];
export const UOMS = ['BOX', 'PCS', 'PACK', 'LITRE', 'KG', 'GALL', 'CAN'];
