/** TEXT dictionary — copied verbatim from "KIS P&L.dc.html" (EN + AR), plus the inline ternary strings the prototype kept in renderVals(). */
export const TEXT = {
  en: {
    title: 'Operational P&L',
    dashboard: 'P&L dashboard', comparison: 'Location comparison', period: 'Period',
    sales: 'Sales (POS)', foodCost: 'Food cost %', waste: 'Waste %', contribution: 'Gross contribution', stockValue: 'Stock value',
    statement: 'P&L statement', movingAvgNote: 'all values at moving-average cost',
    reconciled: 'Reconciled against physical counts', transfersAtCost: 'Transfers at cost',
    transfersIn: 'Transfers in', transfersOut: 'Transfers out', netNote: 'Combined roll-up',
    assembledNote: 'Assembled, not entered',
    assembledBody: 'This P&L computes nothing that was not tracked: receiving (B1), recipes (B3), counts (B2), transfers (B4), and POS consumption (B5) each own their layer. The same skewer’s cost sits in Main Kitchen’s output and Rock’s input without double-counting.',
    export: 'Export', comparePeriods: 'Compare periods', exportToast: 'Export queued — pnl-aug.pdf', compareToast: 'Period comparison — Jul vs Aug (demo)',
    drillToast: 'Opening transactions —', compHint: 'The three locations side by side. Outliers highlighted; click a location to open its full P&L.',
    drillFull: 'Full P&L', outlierNote: 'Worst performer this period: Rock — food cost 28.1% is the highest of the three and its count variance (−$23) is still open. Kaddoum’s waste (2.2%) is above the 2.0% target after the mango-pulp expiry.',
    // outlier note — assembled from the same live figures as the comparison flags so the two never contradict
    outlierLead: 'Worst performer this period:', outlierFoodHigh: 'food cost {p}% is the highest of the three',
    outlierVarOpen: 'and its count variance ({v}) is still open', outlierWasteOver: '{loc}’s waste ({w}%) is above the 2.0% target',
    outlierAllOk: 'All three locations are within their food-cost and waste targets, and counts reconcile.',
    reconciledPill: 'Reconciled', flaggedPill: 'Unreconciled', supplies: 'Production site — supplies Rock & Kaddoum',
    help: 'How this tab works', helpTitle: 'How the P&L is built', gotIt: 'Got it',
    periodTitle: 'Reporting period', byMonth: 'By month', customRange: 'Custom range', from: 'From', to: 'To', apply: 'Apply', cancelBtn: 'Cancel',
    rangeErr: '“To” must be on or after “From”.',
    months: [{ k: '2026-06', l: 'June 2026' }, { k: '2026-07', l: 'July 2026' }, { k: '2026-08', l: 'August 2026' }],
    mon: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    helpIntro: 'This tab assembles — never re-enters — data from receiving, recipes, counts, transfers and POS. Every figure traces back to a tracked transaction, valued at moving-average cost.',
    helpItems: [
      { k: 'Food cost %', v: 'Sales consumption ÷ Sales × 100. Consumption is POS units × recipe cost (B5 × B3), not purchases. Lower is better; target ≤ 28%.' },
      { k: 'Waste %', v: 'Recorded waste value ÷ Sales × 100. Uses logged waste only (B6); target ≤ 2.0%.' },
      { k: 'Gross contribution', v: 'Sales − Sales consumption. What the location keeps before labour and overhead.' },
      { k: 'Stock value', v: 'Ending stock at moving-average cost, reconciled against the physical count (B2).' },
      { k: 'P&L statement', v: 'Beginning + Purchases + Transfers in − Transfers out − Consumption − Waste = Expected ending, then matched to the physical count.' },
      { k: 'Combined view', v: 'The three locations rolled up with transfers netted, so the same item is never counted twice.' },
    ],
    combinedNote: 'transfers netted — no double count', high: 'High', open: 'Open', over: 'Over',
    locs: { mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' }, all: 'Combined',
    // inline strings from renderVals()
    begStock: 'Beginning stock', purchases: 'Purchases', salesCons: 'Sales consumption', wasteRow: 'Waste',
    endStock: 'Ending stock (expected)', physical: 'Physical (counts)', atCost: 'at cost', salesXrecipes: 'sales × recipes', fromB2: 'from B2',
    countVariance: 'Count variance', openVariance: 'open variance', noDirectSales: 'no direct sales', rockKad: 'Rock + Kaddoum',
  },
  ar: {
    title: 'الأرباح والخسائر التشغيلية',
    dashboard: 'لوحة الأرباح والخسائر', comparison: 'مقارنة المواقع', period: 'الفترة',
    sales: 'المبيعات (POS)', foodCost: 'كلفة الطعام ٪', waste: 'الهدر ٪', contribution: 'المساهمة الإجمالية', stockValue: 'قيمة المخزون',
    statement: 'قائمة الأرباح والخسائر', movingAvgNote: 'كل القيم بمتوسط الكلفة المتحرك',
    reconciled: 'مطابقة مع الجرد الفعلي', transfersAtCost: 'التحويلات بالتكلفة',
    transfersIn: 'تحويلات واردة', transfersOut: 'تحويلات صادرة', netNote: 'التجميع الموحد',
    assembledNote: 'مُجمّعة لا مُدخلة',
    assembledBody: 'هذه القائمة لا تحسب شيئاً لم يُتتبع: الاستلام (B1) والوصفات (B3) والجرد (B2) والتحويلات (B4) واستهلاك POS (B5) كلٌ يملك طبقته. كلفة السيخ نفسه تظهر في مخرجات المطبخ الرئيسي ومدخلات روك دون احتساب مزدوج.',
    export: 'تصدير', comparePeriods: 'مقارنة الفترات', exportToast: 'التصدير في الطابور — pnl-aug.pdf', compareToast: 'مقارنة الفترات — تموز مقابل آب (تجريبي)',
    drillToast: 'فتح المعاملات —', compHint: 'المواقع الثلاثة جنباً إلى جنب. القيم الشاذة مميزة؛ انقر موقعاً لفتح قائمته الكاملة.',
    drillFull: 'القائمة الكاملة', outlierNote: 'الأداء الأسوأ هذه الفترة: روك — كلفة الطعام ٢٨٫١٪ الأعلى بين الثلاثة وفرق جرده (−٢٣$) لا يزال مفتوحاً. هدر قدّوم (٢٫٢٪) فوق هدف ٢٫٠٪ بعد انتهاء صلاحية لب المانجو.',
    outlierLead: 'الأداء الأسوأ هذه الفترة:', outlierFoodHigh: 'كلفة الطعام {p}٪ الأعلى بين الثلاثة',
    outlierVarOpen: 'وفرق جرده ({v}) لا يزال مفتوحاً', outlierWasteOver: 'هدر {loc} ({w}٪) فوق هدف ٢٫٠٪',
    outlierAllOk: 'المواقع الثلاثة ضمن أهداف كلفة الطعام والهدر، والجرد مطابق.',
    reconciledPill: 'مطابق', flaggedPill: 'غير مطابق', supplies: 'موقع إنتاج — يزوّد روك وقدّوم',
    help: 'كيف تعمل هذه اللوحة', helpTitle: 'كيف تُبنى قائمة الأرباح والخسائر', gotIt: 'حسناً',
    periodTitle: 'فترة التقرير', byMonth: 'حسب الشهر', customRange: 'مدى مخصّص', from: 'من', to: 'إلى', apply: 'تطبيق', cancelBtn: 'إلغاء',
    rangeErr: 'يجب أن تكون «إلى» في تاريخ مساوٍ أو بعد «من».',
    months: [{ k: '2026-06', l: 'حزيران ٢٠٢٦' }, { k: '2026-07', l: 'تموز ٢٠٢٦' }, { k: '2026-08', l: 'آب ٢٠٢٦' }],
    mon: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    helpIntro: 'هذه اللوحة تُجمّع — ولا تُعيد إدخال — بيانات الاستلام والوصفات والجرد والتحويلات و POS. كل رقم يعود إلى معاملة مُتتبّعة بمتوسط الكلفة المتحرك.',
    helpItems: [
      { k: 'كلفة الطعام ٪', v: 'استهلاك المبيعات ÷ المبيعات × ١٠٠. الاستهلاك = وحدات POS × كلفة الوصفة (B5 × B3)، لا المشتريات. الأقل أفضل؛ الهدف ≤ ٢٨٪.' },
      { k: 'الهدر ٪', v: 'قيمة الهدر المسجّل ÷ المبيعات × ١٠٠. تستخدم الهدر المسجّل فقط (B6)؛ الهدف ≤ ٢٫٠٪.' },
      { k: 'المساهمة الإجمالية', v: 'المبيعات − استهلاك المبيعات. ما يبقى للموقع قبل العمالة والمصاريف.' },
      { k: 'قيمة المخزون', v: 'مخزون النهاية بمتوسط الكلفة، مطابَق مع الجرد الفعلي (B2).' },
      { k: 'قائمة الأرباح والخسائر', v: 'البداية + المشتريات + تحويلات واردة − تحويلات صادرة − استهلاك − هدر = النهاية المتوقعة، ثم تُطابق مع الجرد الفعلي.' },
      { k: 'العرض المجمّع', v: 'المواقع الثلاثة مجمّعة مع مقاصّة التحويلات، فلا يُحتسب الصنف نفسه مرتين.' },
    ],
    combinedNote: 'التحويلات مقاصّة — لا احتساب مزدوج', high: 'مرتفع', open: 'مفتوح', over: 'فوق الهدف',
    locs: { mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' }, all: 'مجمّع',
    begStock: 'مخزون البداية', purchases: 'المشتريات', salesCons: 'استهلاك المبيعات', wasteRow: 'الهدر',
    endStock: 'مخزون النهاية (متوقع)', physical: 'الجرد الفعلي', atCost: 'بالتكلفة', salesXrecipes: 'المبيعات × الوصفات', fromB2: 'من B2',
    countVariance: 'فرق الجرد', openVariance: 'فرق مفتوح', noDirectSales: 'لا مبيعات مباشرة', rockKad: 'روك + قدّوم',
  },
};

export type PnlText = typeof TEXT.en;
