/** TEXT dictionary — copied verbatim from "KIS-Invoice-Review.dc.html", plus keys needed by the store port. */
const en = {
  title: 'Invoice review', userName: 'Rami Haddad', userRole: 'Purchasing · Cost control',
  queueTitle: 'Awaiting review', queueEmpty: 'Queue clear', receivedAt: 'Received',
  invoiceNo: 'Invoice number', invoiceDate: 'Invoice date', supplierVat: 'Supplier VAT reg.',
  receiverFlag: 'Flagged by receiver', scannedInvoice: 'Scanned invoice',
  scanFacsimile: 'Facsimile of the scanned document — compare against your entry',
  noScanTitle: 'No scan attached', noScanBody: 'The receiver submitted with issue. Attach the invoice, then enter or OCR the lines.',
  dropHint: 'Drag & drop a file or photo here, or click to browse / scan', browse: 'Browse file', photo: 'Take photo', scanDoc: 'Scan document', uploaded: 'Attached',
  readItems: 'Read items from invoice (OCR)', manualReadHint: 'OCR reads the attached invoice — verify every line before approving.',
  searchPh: 'Search items to add a line…', noItems: 'No matching item in the catalog.',
  colItem: 'Item', colOrdered: 'Ordered', colQty: 'Invoiced', colPrice: 'Unit price', colTotal: 'Line total', autoBadge: 'OCR', noLines: 'No lines yet — search an item above to add it.',
  subtotal: 'Subtotal', vat: 'VAT', vatRate: 'VAT rate', vatAmount: 'VAT amount', total: 'Total', grandTotal: 'Grand total',
  varTitle: 'Checks', matchExact: 'Entered total matches the scanned invoice.',
  sendBack: 'Send back to receiver', approve: 'Approve & post',
  approveToast: 'Invoice approved — stock & moving-average cost updated', sendToast: 'Sent back to receiver with a note',
  allClearTitle: 'All invoices reviewed', allClearBody: 'Every received delivery has been reconciled and posted. New arrivals from receiving will appear here.',
  matchOffBy: 'Off by', vsInvoice: 'vs scanned invoice',
  tabReview: 'Review', tabSummary: 'Summary', colTimeS: 'Time', colStatusTotal: 'Total',
  tPending: 'Pending', tApproved: 'Approved', tSent: 'Sent back', tApprovedValue: 'Approved value', tVatCollected: 'VAT posted',
  summaryFoot: 'Approving posts the invoice: received quantities enter stock, each item’s moving-average cost is recomputed from the invoice price, and the VAT is booked to the tax ledger. Sent-back invoices return to the receiver and are not posted.',
  needName: 'Enter the supplier name to submit.', needInv: 'Add the invoice number.', needScan: 'Attach the invoice.', needNote: 'Describe the issue.',
  colSupplier: 'Supplier', colInvoice: 'Invoice',
  noNumber: 'no number', scanned: 'Scanned', manual: 'Manual', remove: 'Remove',
  // ── port additions ──
  fAll: 'All', fPending: 'Pending', fDisputed: 'Disputed',
  stageNames: { received: 'Received', entered: 'Entered', review: 'In review', approved: 'Approved', disputed: 'Disputed', paid: 'Paid' },
  noPo: 'No PO', delivery: 'Delivery', noDelivery: 'No delivery linked', stage: 'Stage', colDate: 'Date', received: 'Received', accepted: 'accepted',
  resolve: 'Resolve dispute → back to review', resolveToast: 'Dispute resolved — back in the review queue',
  sbTitle: 'Send back to receiver', sbBody: 'Flags the mismatch (price, quantity or quality) to the receiver and the supplier. The invoice is held as disputed — no payable is created until it is resolved.',
  sbPh: 'Reason (required)…', sbCta: 'Send back — notify', cancel: 'Cancel',
  vsOrdered: 'vs ordered', invoiced: 'invoiced', acceptedAtReceiving: 'accepted at receiving', vsReceivedPrice: 'vs received at', enteredTotal: 'Entered subtotal', deliveryTotal: 'delivery total',
  allAgree: 'Invoice, delivery and PO agree.', storedIssues: 'Open issues on this invoice',
  payableToast: 'Bill created in Accounting payables (ACC-AP-01)',
  lbpNote: 'LBP bill — shown in USD at the day rate',
  auditReview: 'Review started', auditApproved: 'Invoice approved — payable created', auditDisputed: 'Invoice sent back — disputed', auditResolved: 'Dispute resolved',
  alertDisputed: 'sent back to receiver —',
  openPipeline: 'Pipeline',
  // ── real upload (cloud mode) ──
  uploading: 'Uploading…', viewScan: 'View scan', uploadedScan: 'Uploaded scan',
  attachScan: 'Attach real scan', replaceScan: 'Replace', uploadError: 'Upload failed — please try again',
};

export type ReviewText = typeof en;

const ar: ReviewText = {
  title: 'مراجعة الفواتير', userName: 'رامي حداد', userRole: 'المشتريات · مراقبة التكاليف',
  queueTitle: 'بانتظار المراجعة', queueEmpty: 'القائمة فارغة', receivedAt: 'استُلم',
  invoiceNo: 'رقم الفاتورة', invoiceDate: 'تاريخ الفاتورة', supplierVat: 'رقم ضريبة المورد',
  receiverFlag: 'ملاحظة من المستلِم', scannedInvoice: 'الفاتورة الممسوحة',
  scanFacsimile: 'نسخة طبق الأصل من المستند الممسوح — قارنها بإدخالك',
  noScanTitle: 'لا يوجد مسح مرفق', noScanBody: 'أرسل المستلِم مع ملاحظة. أرفق الفاتورة، ثم أدخل الأسطر أو امسحها ضوئياً.',
  dropHint: 'اسحب وأفلت ملفاً أو صورة هنا، أو انقر للتصفح / المسح', browse: 'تصفح ملف', photo: 'التقاط صورة', scanDoc: 'مسح مستند', uploaded: 'مُرفق',
  readItems: 'قراءة الأصناف من الفاتورة (OCR)', manualReadHint: 'يقرأ الـ OCR الفاتورة المرفقة — تحقق من كل سطر قبل الاعتماد.',
  searchPh: 'ابحث عن صنف لإضافة سطر…', noItems: 'لا صنف مطابق في الكتالوج.',
  colItem: 'الصنف', colOrdered: 'المطلوب', colQty: 'المفوتر', colPrice: 'سعر الوحدة', colTotal: 'إجمالي السطر', autoBadge: 'مسح', noLines: 'لا أسطر بعد — ابحث عن صنف أعلاه لإضافته.',
  subtotal: 'المجموع الفرعي', vat: 'ض.ق.م', vatRate: 'نسبة الضريبة', vatAmount: 'قيمة الضريبة', total: 'الإجمالي', grandTotal: 'الإجمالي الكلي',
  varTitle: 'تحققات', matchExact: 'الإجمالي المُدخل يطابق الفاتورة الممسوحة.',
  sendBack: 'إعادة إلى المستلِم', approve: 'اعتماد وترحيل',
  approveToast: 'اعتُمدت الفاتورة — تحدّث المخزون ومتوسط الكلفة', sendToast: 'أُعيدت إلى المستلِم مع ملاحظة',
  allClearTitle: 'روجعت كل الفواتير', allClearBody: 'طوبقت كل التوريدات ورُحّلت. ستظهر الواردات الجديدة من الاستلام هنا.',
  matchOffBy: 'فرق', vsInvoice: 'عن الفاتورة الممسوحة',
  tabReview: 'المراجعة', tabSummary: 'الملخص', colTimeS: 'الوقت', colStatusTotal: 'الإجمالي',
  tPending: 'قيد المراجعة', tApproved: 'معتمدة', tSent: 'أُعيدت', tApprovedValue: 'القيمة المعتمدة', tVatCollected: 'الضريبة المُرحّلة',
  summaryFoot: 'الاعتماد يُرحّل الفاتورة: تدخل الكميات المستلمة المخزون، ويُعاد احتساب متوسط كلفة كل صنف من سعر الفاتورة، وتُقيّد الضريبة في سجل الضرائب. الفواتير المُعادة ترجع إلى المستلِم ولا تُرحّل.',
  needName: 'أدخل اسم المورد.', needInv: 'أضف رقم الفاتورة.', needScan: 'أرفق الفاتورة.', needNote: 'صف الملاحظة.',
  colSupplier: 'المورد', colInvoice: 'الفاتورة',
  noNumber: 'بلا رقم', scanned: 'ممسوحة', manual: 'يدوي', remove: 'إزالة',
  // ── port additions ──
  fAll: 'الكل', fPending: 'قيد المراجعة', fDisputed: 'معترض',
  stageNames: { received: 'مستلمة', entered: 'مُدخلة', review: 'قيد المراجعة', approved: 'معتمدة', disputed: 'معترض', paid: 'مدفوعة' },
  noPo: 'بلا أمر شراء', delivery: 'التسليم', noDelivery: 'لا تسليم مرتبط', stage: 'المرحلة', colDate: 'التاريخ', received: 'المستلم', accepted: 'مقبول',
  resolve: 'حل الاعتراض ← إلى المراجعة', resolveToast: 'حُل الاعتراض — عاد إلى قائمة المراجعة',
  sbTitle: 'إعادة إلى المستلِم', sbBody: 'يعلّم الاختلاف (سعر أو كمية أو جودة) للمستلم والمورد. تُعلّق الفاتورة كمعترض عليها — لا يُنشأ مستحق حتى حلّها.',
  sbPh: 'السبب (إلزامي)…', sbCta: 'إعادة — إبلاغ', cancel: 'إلغاء',
  vsOrdered: 'عن المطلوب', invoiced: 'مفوتر', acceptedAtReceiving: 'مقبول عند الاستلام', vsReceivedPrice: 'مقابل سعر الاستلام', enteredTotal: 'المجموع المُدخل', deliveryTotal: 'إجمالي التسليم',
  allAgree: 'الفاتورة والتسليم وأمر الشراء متطابقة.', storedIssues: 'ملاحظات مفتوحة على هذه الفاتورة',
  payableToast: 'أُنشئت الفاتورة في مستحقات المحاسبة (ACC-AP-01)',
  lbpNote: 'فاتورة بالليرة — تُعرض بالدولار بسعر اليوم',
  auditReview: 'بدأت المراجعة', auditApproved: 'اعتُمدت الفاتورة — أُنشئ المستحق', auditDisputed: 'أُعيدت الفاتورة — معترض', auditResolved: 'حُل الاعتراض',
  alertDisputed: 'أُعيدت إلى المستلِم —',
  openPipeline: 'الخط',
  // ── real upload (cloud mode) ──
  uploading: 'جارٍ الرفع…', viewScan: 'عرض المسح', uploadedScan: 'المسح المرفوع',
  attachScan: 'إرفاق مسح فعلي', replaceScan: 'استبدال', uploadError: 'فشل الرفع — أعد المحاولة',
};

export const TEXT = { en, ar };
