/** TEXT dictionary — copied verbatim from "KIS Reports & Alerts.dc.html" (EN + AR), plus the inline strings the prototype kept in renderVals()/genVals(). */
export const TEXT = {
  en: {
    title: 'Alerts & Reports',
    hub: 'Reporting hub', daily: 'Daily variance', monthly: 'Monthly costing', alerts: 'Alert center', config: 'Thresholds',
    hubHint: 'Reports respect location scope and role permissions', period: 'Period',
    generate: 'Generate', schedule: 'Schedule', hubNote: 'Scheduled reports are emailed as PDF/Excel and always render per-location or combined based on the selector above.',
    dailyT: 'Daily', weeklyT: 'Weekly ', monthlyT: 'Monthly',
    netToday: 'Net variance today', vsYesterday: 'vs yesterday', dayOverDay: 'Net variance · last 7 days',
    item: 'Item', location: 'Location', theoretical: 'Theoretical', actual: 'Actual', impact: '$ impact', evidenceCt: 'Evidence',
    investigate: 'Investigate', assign: 'Assign', drillToast: 'Opening investigation (B6) —', assignToast: 'Corrective action assigned —',
    foodCostActual: 'Food cost % · actual', gap: 'gap', foodCostDollar: 'Food cost $ · month', purchaseVar: 'purchase price variance',
    wastePct: 'Waste %', target: 'target', costMovement: 'Cost movement by category', recipeDrift: 'Recipe cost-% changes',
    profitability: 'Product profitability', sold: 'Sold', revenue: 'Revenue', cost: 'Cost', margin: 'Margin',
    profitNote: 'Best and worst margins highlighted. Drill category → item → recipe.',
    activeAlerts: 'active alerts', configThresholds: 'Configure thresholds', actOn: 'Act', dismiss: 'Dismiss',
    noAlerts: 'No active alerts for this scope.', dismissToast: 'Alert dismissed', actToast: 'Opening —',
    recipeThresholds: 'Per-recipe expected cost %', recipe: 'Recipe', currentPct: 'Current', expectedFood: 'Food % max', expectedPkg: 'Pkg % max',
    globalBands: 'Global KPI bands', warning: 'Warning', critical: 'Critical',
    saveConfig: 'Save thresholds', savedToast: 'Thresholds saved — audit-logged',
    configNote: 'These values drive every status pill and alert system-wide. Changes are audit-logged and apply immediately.',
    sev: { crit: 'Critical', warn: 'Warning', info: 'Info' },
    locs: { mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' }, all: 'All',
    genReady: 'GENERATED', genScope: 'Scope', genPeriod: 'Period', genAt: 'Generated', genBy: 'by You (superuser)', genMetric: 'Metric', genTotal: 'Combined', mk: 'Main K.', kad: 'Kaddoum',
    compare: 'Comparison', cmpTitle: 'Year over year', cmpHint: 'Same month, 2025 vs 2026 · combined locations at the scope above', cmpMetric: 'Metric', cmpDelta: 'Change', cmpChart: 'Net sales by month · 2025 vs 2026', cmpNote: '2025 figures come from closed periods; 2026 from the live ledger. Percentages compare like-for-like calendar months. Aug 2026 is month-to-date and marked accordingly.', mtd: 'MTD', byLoc: 'By location', byPeriod: 'Between periods', from: 'from', to: 'to',
    // inline strings from the prototype script
    week: 'Week ', today: 'Today', yesterday: 'Yesterday', lastDay: 'Last day · ',
    dnames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    linked: 'linked', pdfToast: 'PDF export queued', schedToast: 'Scheduled — weekly · Sun 07:00',
    reportSuffix: ' report', day: ' day', days: ' days', overPill: 'Over', okPill: 'OK', vs: 'vs',
    // alert center additions (assign)
    assignTitle: 'Assign alert', assignTo: 'Assign to', assignedTo: 'Assigned to', assignedAlertToast: 'Alert assigned —', cancel: 'Cancel',
    thresholdsAudit: 'Thresholds saved', unchanged: 'no changes',
  },
  ar: {
    title: 'التنبيهات والتقارير',
    hub: 'مركز التقارير', daily: 'الفروقات اليومية', monthly: 'التكاليف الشهرية', alerts: 'مركز التنبيهات', config: 'الحدود',
    hubHint: 'التقارير تراعي نطاق الموقع وصلاحيات الدور', period: 'الفترة',
    generate: 'إنشاء', schedule: 'جدولة', hubNote: 'التقارير المجدولة تُرسل PDF/Excel وتُعرض دائماً لكل موقع أو مجمّعة حسب المحدد أعلاه.',
    dailyT: 'يومي', weeklyT: 'أسبوعي', monthlyT: 'شهري',
    netToday: 'صافي فرق اليوم', vsYesterday: 'مقابل الأمس', dayOverDay: 'صافي الفرق · آخر ٧ أيام',
    item: 'الصنف', location: 'الموقع', theoretical: 'النظري', actual: 'الفعلي', impact: 'الأثر $', evidenceCt: 'الأدلة',
    investigate: 'تحقيق', assign: 'إسناد', drillToast: 'فتح التحقيق (B6) —', assignToast: 'أُسند إجراء تصحيحي —',
    foodCostActual: 'نسبة كلفة الطعام · فعلي', gap: 'الفجوة', foodCostDollar: 'كلفة الطعام $ · الشهر', purchaseVar: 'فرق أسعار الشراء',
    wastePct: 'نسبة الهدر', target: 'الهدف', costMovement: 'حركة الكلفة حسب الفئة', recipeDrift: 'تغيرات نسبة كلفة الوصفات',
    profitability: 'ربحية المنتجات', sold: 'مبيع', revenue: 'الإيراد', cost: 'الكلفة', margin: 'الهامش',
    profitNote: 'أفضل وأسوأ الهوامش مميزة. التعمق: فئة ← صنف ← وصفة.',
    activeAlerts: 'تنبيهات فعالة', configThresholds: 'إعداد الحدود', actOn: 'تصرّف', dismiss: 'تجاهل',
    noAlerts: 'لا تنبيهات فعالة لهذا النطاق.', dismissToast: 'تم تجاهل التنبيه', actToast: 'فتح —',
    recipeThresholds: 'نسبة الكلفة المتوقعة لكل وصفة', recipe: 'الوصفة', currentPct: 'الحالية', expectedFood: 'حد الطعام %', expectedPkg: 'حد التغليف %',
    globalBands: 'نطاقات KPI العامة', warning: 'تحذير', critical: 'حرج',
    saveConfig: 'حفظ الحدود', savedToast: 'حُفظت الحدود — سُجلت في التدقيق',
    configNote: 'هذه القيم تقود كل مؤشرات الحالة والتنبيهات في النظام. التغييرات تُسجل وتسري فوراً.',
    sev: { crit: 'حرج', warn: 'تحذير', info: 'معلومة' },
    locs: { mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' }, all: 'الكل',
    genReady: 'مُنشأ', genScope: 'النطاق', genPeriod: 'الفترة', genAt: 'أُنشئ', genBy: 'بواسطتك (مستخدم متميز)', genMetric: 'المؤشر', genTotal: 'مجمّع', mk: 'الرئيسي', kad: 'قدّوم',
    compare: 'مقارنة', cmpTitle: 'سنة مقابل سنة', cmpHint: 'الشهر نفسه، ٢٠٢٥ مقابل ٢٠٢٦ · حسب النطاق أعلاه', cmpMetric: 'المؤشر', cmpDelta: 'التغير', cmpChart: 'صافي المبيعات شهرياً · ٢٠٢٥ مقابل ٢٠٢٦', cmpNote: 'أرقام ٢٠٢٥ من فترات مقفلة؛ ٢٠٢٦ من السجل الحي. النسب تقارن الأشهر التقويمية المتماثلة. آب ٢٠٢٦ حتى تاريخه ومُعلَّم بذلك.', mtd: 'حتى تاريخه', byLoc: 'حسب الموقع', byPeriod: 'بين فترتين', from: 'من', to: 'إلى',
    week: 'أسبوع ', today: 'اليوم', yesterday: 'أمس', lastDay: 'آخر يوم · ',
    dnames: ['الأحد', 'الإثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
    linked: 'روابط', pdfToast: 'تصدير PDF في الطابور', schedToast: 'جُدول أسبوعياً · الأحد ٠٧:٠٠',
    reportSuffix: ' — تقرير', day: ' يوم', days: ' يوم', overPill: 'فوق الحد', okPill: 'OK', vs: 'vs',
    assignTitle: 'إسناد التنبيه', assignTo: 'إسناد إلى', assignedTo: 'مُسند إلى', assignedAlertToast: 'أُسند التنبيه —', cancel: 'إلغاء',
    thresholdsAudit: 'حُفظت الحدود', unchanged: 'لا تغييرات',
  },
};

export type RptText = typeof TEXT.en;
