/** TEXT dictionary — copied verbatim from "KIS Recipes.dc.html" (inline strings from renderVals included). */
const en = {
  recipes: 'Recipes', totalRecipes: 'Total recipes', overThreshold: 'Over cost-% threshold', biggestMover: 'Biggest cost mover today',
  searchPh: 'Search recipes…', newRecipe: 'New recipe', recipe: 'Recipe', type: 'Type', yield: 'Yield', currentCost: 'Current cost',
  price: 'Price', foodPct: 'Food cost %', pkgPct: 'Packaging %', status: 'Status', all: 'All',
  builder: 'Builder', versions: 'Version history', saveVersion: 'Save new version',
  foodLines: 'Ingredients & sub-recipes', pkgLines: 'Packaging (tracked separately)', ingredient: 'Item', qty: 'Qty',
  unitCost: 'Unit cost', lineCost: 'Line cost', addLine: 'Add line', subBadge: 'SUB', kindIng: 'Ingredient', kindPkg: 'Packaging', batchYield: 'Total production (batch yield)', batchCost: 'Batch cost', batchYieldNote: 'How much one full batch produces, in its UOM. Per-unit cost = batch cost ÷ this quantity — it\'s what recipes consuming this sub-recipe are charged.', priceMissing: 'No selling price posted yet — food-cost % can\'t be computed. Set it here or in menu settings.', xferTitle: 'Transfer pricing (if transferred)', xferProfit: 'Profit vs cost', foodProfitVal: 'Food profit', foodProfitPct: 'Food profit %', howCalc: 'How is this calculated?', fcHelpFormula: 'Food cost % = food cost ÷ selling price × 100', pkgHelpFormula: 'Packaging % = packaging cost ÷ selling price × 100', fpHelpFormula: 'Food profit = selling price − food cost', fppHelpFormula: 'Food profit % = food profit ÷ selling price × 100', fcHelpBody: 'Food cost is the live built-up cost of ingredient lines only (packaging is tracked separately). Selling price is the posted price above. Ingredient costs use each item\'s moving average, so this % moves when purchase prices move — an alert fires when it crosses the threshold.', xferCostPct: 'Cost ÷ transfer price', xferProfitVal: 'Profit value', xferProfitPct: 'Profit %', xferOwnCost: 'Cost before transfer', xferRecvCost: 'Cost after transfer (receiving location)',
  builtUpCost: 'Built-up cost · live', prevCost: 'Previous version', foodCost: 'Food cost', pkgCost: 'Packaging cost',
  sellingPrice: 'Selling price', threshold: 'threshold', current: 'CURRENT',
  costNote: 'How this cost is built', costNoteBody: 'Each line converts its recipe unit to the item’s base unit and prices it at moving-average cost. Sub-recipe lines carry their own built-up cost from their location of production.',
  editQtyIn: 'Quantity in', cancel: 'Cancel', apply: 'Apply',
  reasonRequired: 'A reason is required — versioning is mandatory, no silent edits.',
  reasonPh: 'e.g. Increased fries portion 140 g → 150 g',
  versionWarning: 'Historical transactions keep the version active at their time. The new version applies from now on.',
  saveAsNew: 'Save as new version', costAtVersion: 'cost', txnsUsed: 'transactions used it',
  versionRule: 'Append-only and effective-dated. Select a version to see its diff against the previous one.',
  costChange: 'Cost change', diffVs: 'vs', withinTolerance: 'Within threshold', overBand: 'Over threshold — alert raised',
  statusOk: 'OK', statusOver: 'Over threshold',
  types: { sub: 'Sub-recipe', recipe: 'Recipe', prep: 'Prepared', menu: 'Menu item' },
  // inline strings from renderVals
  kpiMover: 'Marinated taouk skewer +$0.01 (chicken avg ↑)',
  xNoteHas: 'Receiving locations are charged this price instead of cost — the spread shows as Main Kitchen profit in the P&L.',
  xNoteEmpty: 'Empty = transfers at cost (Rule 12, the default). Set a price only if this item is sold internally with a margin.',
  formNewRecipe: 'New recipe', formAddLine: 'Add line — ',
  formSubRecipe: 'Quick form — ingredients are added in the builder after creation.',
  formSubLine: 'Unit cost is imported from the item list by mapping — never typed by hand.',
  fp1Recipe: 'Name — e.g. Falafel wrap', fp1Line: '…or type to search — e.g. Tahini',
  fp2: 'Qty only — unit comes from the mapped item',
  fp3: 'Selling price $ (menu item, optional)',
  pickFromList: '— pick from the list —',
  mapItem: 'Mapped item — moving avg', mapPkg: 'Packaging item', mapLive: ' — live per-unit cost', mapping: 'Mapping',
  mapIdle: 'Type the ingredient name above…', mapNone: 'No matching item',
  missPkg: 'No matching packaging item — create it first in', missIng: 'Costs are never typed here — create the item first in',
  missRecipeA: 'No matching ', missRecipeB: ' — create it first via “New recipe”', itemsCta: 'Items & UOM',
  typeChips: [
    { k: 'menu', label: 'Menu item', sub: 'Sold at the register' },
    { k: 'recipe', label: 'Recipe', sub: 'Built from sub-recipes & items' },
    { k: 'prep', label: 'Prepared (transfer item)', sub: 'Made centrally, transferred out' },
    { k: 'sub', label: 'Sub-recipe', sub: 'Base batch from inventory items' },
  ] as { k: 'menu' | 'recipe' | 'prep' | 'sub'; label: string; sub: string }[],
  typeHint: {
    menu: 'Appears on the register once published, yields 1 PCS. Connects recipes, prepared items and inventory items; packaging is tracked separately.',
    recipe: 'Connects sub-recipes and inventory items. Set its batch yield in the builder.',
    prep: 'Produced at Main Kitchen and transferred to locations at cost. Connects recipes and items.',
    sub: 'The base building block — built from inventory items only, yields a batch (e.g. 8 KG marinade).',
  },
  formWarnRecipe: 'Created as version v1 with reason "Initial recipe" — versioning is mandatory from the start.',
  formWarnLine: 'A structural edit — save a new version with a reason before it counts operationally.',
  ctaRecipe: 'Create recipe', ctaLine: 'Add line',
  yieldTbd: '? — set in builder', you: 'You (superuser)', initialRecipe: 'Initial recipe',
  toastRecipe: 'Recipe created as v1 — add ingredients', toastPkg: 'Packaging line added — tracked separately', toastLine: 'Line added — cost recomputed',
  toastSaved: 'Version saved — cost updated on the item',
  pkgSuffix: ' (packaging)', dSellingPrice: 'Selling price', dThreshold: 'Food-cost threshold', dBatchYield: 'Batch yield', dXfer: 'Transfer price', atCost: 'at cost', noStructural: 'No structural changes',
};

export type RecipesText = typeof en;

const ar: RecipesText = {
  recipes: 'الوصفات', totalRecipes: 'إجمالي الوصفات', overThreshold: 'فوق حد نسبة الكلفة', biggestMover: 'أكبر تغير كلفة اليوم',
  searchPh: 'ابحث في الوصفات…', newRecipe: 'وصفة جديدة', recipe: 'الوصفة', type: 'النوع', yield: 'الإنتاجية', currentCost: 'الكلفة الحالية',
  price: 'السعر', foodPct: 'نسبة كلفة الطعام', pkgPct: 'نسبة التغليف', status: 'الحالة', all: 'الكل',
  builder: 'المنشئ', versions: 'سجل الإصدارات', saveVersion: 'حفظ إصدار جديد',
  foodLines: 'المكونات والوصفات الفرعية', pkgLines: 'التغليف (يُتتبع منفصلاً)', ingredient: 'الصنف', qty: 'الكمية',
  unitCost: 'كلفة الوحدة', lineCost: 'كلفة السطر', addLine: 'إضافة سطر', subBadge: 'فرعية', kindIng: 'مكوّن', kindPkg: 'تغليف', batchYield: 'إجمالي الإنتاج (إنتاجية الدفعة)', batchCost: 'كلفة الدفعة', batchYieldNote: 'كم تنتج الدفعة الكاملة بوحدتها. كلفة الوحدة = كلفة الدفعة ÷ هذه الكمية — وهي ما يُحمَّل على الوصفات التي تستهلك هذه الوصفة الفرعية.', priceMissing: 'لم يُنشر سعر بيع بعد — لا يمكن حساب نسبة كلفة الطعام. حدّده هنا أو في إعدادات القائمة.', xferTitle: 'تسعير التحويل (عند التحويل)', xferProfit: 'الربح مقابل الكلفة', foodProfitVal: 'ربح الطعام', foodProfitPct: 'ربح الطعام ٪', howCalc: 'كيف تُحسب؟', fcHelpFormula: 'كلفة الطعام ٪ = كلفة الطعام ÷ سعر البيع × ١٠٠', pkgHelpFormula: 'التغليف ٪ = كلفة التغليف ÷ سعر البيع × ١٠٠', fpHelpFormula: 'ربح الطعام = سعر البيع − كلفة الطعام', fppHelpFormula: 'ربح الطعام ٪ = ربح الطعام ÷ سعر البيع × ١٠٠', fcHelpBody: 'كلفة الطعام هي الكلفة المتراكمة الحية لسطور المكونات فقط (التغليف يُتتبع منفصلاً). سعر البيع هو السعر المنشور أعلاه. كلف المكونات بالمتوسط المتحرك، لذا تتحرك النسبة مع أسعار الشراء — وينطلق تنبيه عند تجاوز الحد.', xferCostPct: 'الكلفة ÷ سعر التحويل', xferProfitVal: 'قيمة الربح', xferProfitPct: 'الربح ٪', xferOwnCost: 'الكلفة قبل التحويل', xferRecvCost: 'الكلفة بعد التحويل (الموقع المستلم)',
  builtUpCost: 'الكلفة المتراكمة · مباشر', prevCost: 'الإصدار السابق', foodCost: 'كلفة الطعام', pkgCost: 'كلفة التغليف',
  sellingPrice: 'سعر البيع', threshold: 'الحد', current: 'الحالي',
  costNote: 'كيف تُبنى هذه الكلفة', costNoteBody: 'كل سطر يحوّل وحدة الوصفة إلى وحدة أساس الصنف ويسعّرها بمتوسط الكلفة المتحرك. أسطر الوصفات الفرعية تحمل كلفتها المتراكمة من موقع إنتاجها.',
  editQtyIn: 'الكمية بوحدة', cancel: 'إلغاء', apply: 'تطبيق',
  reasonRequired: 'السبب إلزامي — الإصدارات إجبارية، لا تعديلات صامتة.',
  reasonPh: 'مثال: زيادة حصة البطاطا من ١٤٠ غ إلى ١٥٠ غ',
  versionWarning: 'المعاملات التاريخية تحتفظ بالإصدار الساري وقتها. الإصدار الجديد يسري من الآن.',
  saveAsNew: 'حفظ كإصدار جديد', costAtVersion: 'الكلفة', txnsUsed: 'معاملة استخدمته',
  versionRule: 'سجل إلحاقي بتواريخ سريان. اختر إصداراً لرؤية فرقه عن السابق.',
  costChange: 'تغير الكلفة', diffVs: 'مقابل', withinTolerance: 'ضمن الحد', overBand: 'فوق الحد — تم إصدار تنبيه',
  statusOk: 'سليم', statusOver: 'فوق الحد',
  types: { sub: 'وصفة فرعية', recipe: 'وصفة', prep: 'مُحضّر', menu: 'صنف قائمة' },
  kpiMover: 'سيخ طاووق متبّل +$0.01 (chicken avg ↑)',
  xNoteHas: 'المواقع المستلمة تُحمَّل هذا السعر بدل الكلفة — الفرق يظهر ربحاً للمطبخ الرئيسي في قائمة الأرباح.',
  xNoteEmpty: 'فارغ = التحويل بالكلفة (القاعدة ١٢، الافتراضي). حدّد سعراً فقط إذا كان هذا الصنف يُباع داخلياً بهامش.',
  formNewRecipe: 'وصفة جديدة', formAddLine: 'إضافة سطر — ',
  formSubRecipe: 'نموذج سريع — المكونات تُضاف في المنشئ بعد الإنشاء.',
  formSubLine: 'كلفة الوحدة تُستورد من قائمة الأصناف بالربط — لا إدخال يدوي للكلفة.',
  fp1Recipe: 'الاسم — مثال: Falafel wrap', fp1Line: '…أو اكتب للبحث — مثال: Tahini',
  fp2: 'الكمية فقط — الوحدة من الصنف المربوط',
  fp3: 'سعر البيع $ (لصنف قائمة، اختياري)',
  pickFromList: '— اختر من القائمة —',
  mapItem: 'مربوط بصنف — متوسط متحرك', mapPkg: 'صنف تغليف', mapLive: ' — كلفة الوحدة الحية', mapping: 'الربط',
  mapIdle: 'اكتب اسم المكوّن أعلاه…', mapNone: 'لا صنف مطابق',
  missPkg: 'لا صنف تغليف مطابق — أنشئه أولاً في', missIng: 'الكلفة لا تُدخل يدوياً — أنشئ الصنف أولاً في',
  missRecipeA: 'لا ', missRecipeB: ' مطابقة — أنشئها أولاً من «وصفة جديدة»', itemsCta: 'الأصناف والوحدات',
  typeChips: [
    { k: 'menu', label: 'صنف قائمة', sub: 'يُباع على الصندوق' },
    { k: 'recipe', label: 'وصفة', sub: 'تُبنى من وصفات فرعية وأصناف' },
    { k: 'prep', label: 'مُحضّر (صنف تحويل)', sub: 'يُنتج مركزياً ويُحوَّل' },
    { k: 'sub', label: 'وصفة فرعية', sub: 'دفعة أساس من أصناف المخزون' },
  ],
  typeHint: {
    menu: 'يظهر على الصندوق فور النشر بإنتاجية 1 PCS. يربط وصفات ومُحضّرات وأصنافاً، والتغليف يُتتبع منفصلاً.',
    recipe: 'تربط وصفات فرعية وأصنافاً من المخزون. حدّد إنتاجية الدفعة في المنشئ.',
    prep: 'يُنتج في المطبخ الرئيسي ويُحوَّل للمواقع بالكلفة. يربط وصفات وأصنافاً.',
    sub: 'اللبنة الأساس — تُبنى من أصناف المخزون فقط وتنتج دفعة (مثل 8 KG تتبيلة).',
  },
  formWarnRecipe: 'تُنشأ كإصدار v1 بسبب «وصفة أولية» — الإصدارات إلزامية من البداية.',
  formWarnLine: 'تعديل بنيوي — احفظ إصداراً جديداً بسبب قبل اعتماده تشغيلياً.',
  ctaRecipe: 'إنشاء الوصفة', ctaLine: 'إضافة السطر',
  yieldTbd: '؟ — تُحدد في المنشئ', you: 'أنت (مستخدم متميز)', initialRecipe: 'الوصفة الأولية',
  toastRecipe: 'أُنشئت الوصفة v1 — أضف المكونات', toastPkg: 'أُضيف سطر التغليف — يُتتبع منفصلاً', toastLine: 'أُضيف السطر — أُعيد حساب الكلفة',
  toastSaved: 'حُفظ الإصدار — حُدّثت كلفة الصنف',
  pkgSuffix: ' (تغليف)', dSellingPrice: 'سعر البيع', dThreshold: 'حد كلفة الطعام', dBatchYield: 'إنتاجية الدفعة', dXfer: 'سعر التحويل', atCost: 'بالكلفة', noStructural: 'لا تغييرات بنيوية',
};

export const TEXT = { en, ar };
