/** MGT-RCV-02 / MGT-RCV-03 — Receiving Oversight. EN/AR copied verbatim from the prototype, plus keys for the ported store actions. */
export const TEXT = {
  en: {
    title: 'Receiving',
    deliveries: 'Deliveries', ppv: 'Purchase price variance', receivedToday: 'Received today', deliveriesK: 'Deliveries',
    priceAlerts: 'Price alerts', rejected: 'Rejected items', date: 'Date', supplier: 'Supplier', invoice: 'Invoice',
    location: 'Location', lines: 'Lines', total: 'Total', worstPv: 'Worst price var.', receivedBy: 'Received by',
    item: 'Item', ordRecv: 'Ord → Recv', price: 'Price', varPct: 'Var %', avgCostMove: 'Avg cost old → new', batchExp: 'Batch · Expiry',
    adjustLine: 'Adjust a line', export: 'Export', immutableNote: 'Immutable once posted — corrections are adjustments.',
    adjustBody: 'Adjustments are approval-gated and audit-logged. Describe the correction.',
    adjustPh: 'e.g. Line 2: received 9 CAN not 10 — one leaked', adjustWarn: 'The original delivery stays immutable; an adjustment movement is created on approval.',
    requestApproval: 'Request approval', cancel: 'Cancel', adjustToast: 'Adjustment sent for approval', exportToast: 'Export queued',
    biggestMovers: 'Biggest movers this period', lastCurrent: 'Last → Current', setThresholds: 'Set thresholds (B7)',
    baseline: 'last agreed price', today: 'today', amberBand: 'amber', redBand: 'red',
    ppvNote: 'Chart shows each receipt price vs the last agreed price with threshold bands. Click a mover to load its chart.',
    thresholdToast: 'Opening threshold config (MGT-RPT-05)', all: 'All',
    pricePer: 'price per',
    // ported additions
    noDeliveries: 'No deliveries in this scope.', base: 'base', rejectedQuality: 'rejected (quality)',
    adjLine: 'Line', adjNewQty: 'Corrected received qty', adjReason: 'Reason',
    approveTitle: 'Approve adjustment?', approveBody: 'An adjustment movement is posted for the difference, the delivery is marked adjusted and the change is written to the audit trail.', approveCta: 'Approve & post',
    adjustedToast: 'Adjustment posted', needAdjust: 'Enter a corrected quantity and a reason.',
    openItem: 'Open item', openSupplier: 'Open supplier', prev: 'prev', adjusted: 'adjusted',
    adjMove: 'Adjustment',
    viewScan: 'View scan', invoiceScan: 'Invoice scan',
  },
  ar: {
    title: 'الاستلام',
    deliveries: 'التسليمات', ppv: 'فروقات أسعار الشراء', receivedToday: 'المستلم اليوم', deliveriesK: 'التسليمات',
    priceAlerts: 'تنبيهات الأسعار', rejected: 'أصناف مرفوضة', date: 'التاريخ', supplier: 'المورد', invoice: 'الفاتورة',
    location: 'الموقع', lines: 'الأسطر', total: 'الإجمالي', worstPv: 'أسوأ فرق سعر', receivedBy: 'استلمه',
    item: 'الصنف', ordRecv: 'مطلوب ← مستلم', price: 'السعر', varPct: 'الفرق ٪', avgCostMove: 'متوسط الكلفة قديم ← جديد', batchExp: 'الدفعة · الصلاحية',
    adjustLine: 'تسوية سطر', export: 'تصدير', immutableNote: 'غير قابل للتعديل بعد الترحيل — التصحيحات تسويات.',
    adjustBody: 'التسويات تتطلب موافقة وتُسجل في التدقيق. صف التصحيح.',
    adjustPh: 'مثال: السطر ٢: استُلمت ٩ تنكات لا ١٠ — واحدة مسربة', adjustWarn: 'يبقى التسليم الأصلي غير قابل للتعديل؛ تُنشأ حركة تسوية عند الموافقة.',
    requestApproval: 'طلب موافقة', cancel: 'إلغاء', adjustToast: 'أُرسلت التسوية للموافقة', exportToast: 'التصدير في الطابور',
    biggestMovers: 'أكبر التغيرات هذه الفترة', lastCurrent: 'السابق ← الحالي', setThresholds: 'ضبط الحدود (B7)',
    baseline: 'آخر سعر متفق', today: 'اليوم', amberBand: 'كهرماني', redBand: 'أحمر',
    ppvNote: 'الرسم يعرض سعر كل استلام مقابل آخر سعر متفق مع نطاقات الحدود. انقر أي صنف لعرض رسمه.',
    thresholdToast: 'فتح إعداد الحدود (MGT-RPT-05)', all: 'الكل',
    pricePer: 'السعر لكل',
    noDeliveries: 'لا تسليمات في هذا النطاق.', base: 'أساسي', rejectedQuality: 'مرفوضة (جودة)',
    adjLine: 'السطر', adjNewQty: 'الكمية المستلمة المصححة', adjReason: 'السبب',
    approveTitle: 'الموافقة على التسوية؟', approveBody: 'تُرحّل حركة تسوية بالفرق، ويُعلّم التسليم كمسوّى، ويُسجل التغيير في سجل التدقيق.', approveCta: 'اعتماد وترحيل',
    adjustedToast: 'رُحّلت التسوية', needAdjust: 'أدخل الكمية المصححة والسبب.',
    openItem: 'فتح الصنف', openSupplier: 'فتح المورد', prev: 'السابق', adjusted: 'مسوّى',
    adjMove: 'تسوية',
    viewScan: 'عرض المسح', invoiceScan: 'مسح الفاتورة',
  },
} as const;

export type RcvText = typeof TEXT['en'];
