/** TEXT dictionary — copied verbatim from "KIS Users, Locations & Suppliers.dc.html", plus keys the store port needs. */
const en = {
  users: 'Users', locations: 'Locations', suppliers: 'Suppliers',
  searchUsers: 'Search users…', newUser: 'New user', name: 'Name', role: 'Role', scope: 'Location scope',
  credentials: 'Credentials', status: 'Status', credType: 'Credential type', lastActive: 'Last active',
  permPreview: 'Permission preview (from role)', permNote: 'Derived from the role matrix (MGT-AUTH-03) — not editable per user.',
  resetPin: 'Reset PIN', resetPassword: 'Reset password', resetNote: 'does not expose secrets',
  deactivate: 'Deactivate user', reactivate: 'Reactivate user',
  deacNote: 'Deactivate only — history is preserved. All changes audit-logged.',
  active: 'Active', inactive: 'Inactive', pin: 'PIN', emailCred: 'Email + 2FA',
  locHint: 'Each location is an independent stock ledger with its own P&L. Never hard-deleted — deactivate only.',
  responsibilities: 'Responsibilities', storageAreas: 'Storage areas', edit: 'Edit',
  locNote: 'A location with history cannot be deleted. Storage areas refine where counts and stock cards point.',
  newSupplier: 'New supplier', contact: 'Contact', terms: 'Payment terms', spend30: 'Spend · 30d',
  productsSupplied: 'Products supplied', product: 'Product', unit: 'Unit', lastPrice: 'Last price',
  trend90: '90-day trend', lastDelivery: 'Last delivery', priceHistory: 'Price history', openPpv: 'Open price variance (D1)',
  invoiceHistory: 'Invoice history', outstanding: 'Outstanding', colInvNo: 'Invoice', colDate: 'Date', colValue: 'Value', colVat: 'VAT', paid: 'Paid', due: 'Due',
  invToast: 'Opening invoice in review pipeline (PUR-INV-01)',
  today: 'today', resetToast: 'Reset link / PIN issued — audit-logged', savedToast: 'Saved — audit-logged',
  newToast: 'New record form — demo', ppvToast: 'Opening purchase price variance (MGT-RCV-03)',
  deacToast: 'User deactivated — history preserved', reacToast: 'User reactivated',
  roles: { super: 'Superuser', owner: 'Owner', mgr: 'Kitchen Manager', store: 'Storekeeper', prep: 'Preparation', prod: 'Production', serve: 'Service', acct: 'Accountant', inv: 'Invoice employee', cost: 'Cost controller' },
  locs: { all: 'All locations', mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' },
  // ── port additions ──
  types: { production: 'Production hub', restaurant: 'Service + line cooking', juice: 'Juices & desserts' },
  stockValue: 'Stock value', itemsSuffix: 'items', noProducts: 'No products linked yet.', noInvoices: 'No invoices for this supplier.', noUsers: 'No users match.',
  stages: { received: 'Received', entered: 'Entered', review: 'In review', approved: 'Due', disputed: 'Disputed', paid: 'Paid' },
  dueLbl: 'due', cancel: 'Cancel', save: 'Save', activeLbl: 'Active',
  nuTitle: 'New user', nameEn: 'Name (EN)', nameArLbl: 'Name (AR)', credential: 'Credential', createUser: 'Create user', needName: 'Enter a name.',
  nuNote: 'A PIN is issued for tablet roles; password + 2FA for management roles.',
  editLoc: 'Edit location', respHint: 'Comma-separated', areasHint: 'Comma-separated',
  nsTitle: 'New supplier', editSup: 'Edit supplier', phone: 'Phone', createSup: 'Create supplier',
  supDeacToast: 'Supplier deactivated — history preserved', supReacToast: 'Supplier reactivated',
  auditUserCreated: 'User created', auditUserDeactivated: 'User deactivated', auditUserReactivated: 'User reactivated',
  auditResetPin: 'PIN reset issued', auditResetPassword: 'Password reset issued', auditLocUpdated: 'Location updated',
  auditSupCreated: 'Supplier created', auditSupUpdated: 'Supplier updated',
};

export type MasterText = typeof en;

const ar: MasterText = {
  users: 'المستخدمون', locations: 'المواقع', suppliers: 'الموردون',
  searchUsers: 'ابحث في المستخدمين…', newUser: 'مستخدم جديد', name: 'الاسم', role: 'الدور', scope: 'نطاق الموقع',
  credentials: 'الاعتماد', status: 'الحالة', credType: 'نوع الاعتماد', lastActive: 'آخر نشاط',
  permPreview: 'معاينة الصلاحيات (من الدور)', permNote: 'مشتقة من مصفوفة الأدوار (MGT-AUTH-03) — لا تُعدّل لكل مستخدم.',
  resetPin: 'إعادة تعيين الرمز', resetPassword: 'إعادة تعيين كلمة المرور', resetNote: 'لا يكشف الأسرار',
  deactivate: 'تعطيل المستخدم', reactivate: 'إعادة تفعيل المستخدم',
  deacNote: 'تعطيل فقط — يُحفظ التاريخ. كل التغييرات تُسجل بالتدقيق.',
  active: 'فعّال', inactive: 'معطّل', pin: 'رمز PIN', emailCred: 'بريد + تحقق ثنائي',
  locHint: 'كل موقع دفتر مخزون مستقل بأرباحه وخسائره. لا حذف نهائي — تعطيل فقط.',
  responsibilities: 'المسؤوليات', storageAreas: 'مناطق التخزين', edit: 'تعديل',
  locNote: 'موقع له تاريخ لا يُحذف. مناطق التخزين تدقق وجهة الجرد وبطاقات المخزون.',
  newSupplier: 'مورد جديد', contact: 'جهة الاتصال', terms: 'شروط الدفع', spend30: 'الإنفاق · ٣٠ يوماً',
  productsSupplied: 'الأصناف الموردة', product: 'الصنف', unit: 'الوحدة', lastPrice: 'آخر سعر',
  trend90: 'اتجاه ٩٠ يوماً', lastDelivery: 'آخر تسليم', priceHistory: 'تاريخ الأسعار', openPpv: 'فتح فروقات الأسعار (D1)',
  invoiceHistory: 'سجل الفواتير', outstanding: 'المستحق', colInvNo: 'الفاتورة', colDate: 'التاريخ', colValue: 'القيمة', colVat: 'الضريبة', paid: 'مدفوعة', due: 'مستحقة',
  invToast: 'فتح الفاتورة في خط المراجعة (PUR-INV-01)',
  today: 'اليوم', resetToast: 'صدر رابط/رمز إعادة التعيين — سُجل بالتدقيق', savedToast: 'حُفظ — سُجل بالتدقيق',
  newToast: 'نموذج سجل جديد — تجريبي', ppvToast: 'فتح فروقات أسعار الشراء (MGT-RCV-03)',
  deacToast: 'عُطّل المستخدم — التاريخ محفوظ', reacToast: 'أُعيد تفعيل المستخدم',
  roles: { super: 'مستخدم متميز', owner: 'المالك', mgr: 'مدير المطبخ', store: 'أمين المخزن', prep: 'التحضير', prod: 'الإنتاج', serve: 'الخدمة', acct: 'محاسب', inv: 'موظف الفواتير', cost: 'مراقب التكاليف' },
  locs: { all: 'كل المواقع', mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' },
  // ── port additions ──
  types: { production: 'مركز إنتاج', restaurant: 'خدمة وطهي مباشر', juice: 'عصائر وحلويات' },
  stockValue: 'قيمة المخزون', itemsSuffix: 'أصناف', noProducts: 'لا أصناف مرتبطة بعد.', noInvoices: 'لا فواتير لهذا المورد.', noUsers: 'لا مستخدمين مطابقين.',
  stages: { received: 'مستلمة', entered: 'مُدخلة', review: 'قيد المراجعة', approved: 'مستحقة', disputed: 'معترض', paid: 'مدفوعة' },
  dueLbl: 'الاستحقاق', cancel: 'إلغاء', save: 'حفظ', activeLbl: 'فعّال',
  nuTitle: 'مستخدم جديد', nameEn: 'الاسم (EN)', nameArLbl: 'الاسم (AR)', credential: 'الاعتماد', createUser: 'إنشاء المستخدم', needName: 'أدخل الاسم.',
  nuNote: 'يُصدر رمز PIN لأدوار التابلت؛ كلمة مرور + تحقق ثنائي لأدوار الإدارة.',
  editLoc: 'تعديل الموقع', respHint: 'مفصولة بفواصل', areasHint: 'مفصولة بفواصل',
  nsTitle: 'مورد جديد', editSup: 'تعديل المورد', phone: 'الهاتف', createSup: 'إنشاء المورد',
  supDeacToast: 'عُطّل المورد — التاريخ محفوظ', supReacToast: 'أُعيد تفعيل المورد',
  auditUserCreated: 'أُنشئ مستخدم', auditUserDeactivated: 'عُطّل المستخدم', auditUserReactivated: 'أُعيد تفعيل المستخدم',
  auditResetPin: 'صدر إعادة تعيين الرمز', auditResetPassword: 'صدر إعادة تعيين كلمة المرور', auditLocUpdated: 'حُدّث الموقع',
  auditSupCreated: 'أُنشئ مورد', auditSupUpdated: 'حُدّث المورد',
};

export const TEXT = { en, ar };
