/** STF-RCV-01 — Receiving Entry (staff). EN/AR copied verbatim from the prototype, plus keys for product lines, confirmation and the done screen. */
export const TEXT = {
  en: {
    title: 'Receiving', mk: 'Main Kitchen', userName: 'Ziad', userRole: 'Store · Receiver',
    tabDeliv: 'Deliveries', tabSummary: 'Day summary',
    expectedToday: 'Expected today', fromPurchasing: 'from purchasing requests',
    arrivedTitle: 'Supplier arrived — not on the list', arrivedSub: 'Log a delivery from a supplier purchasing didn’t schedule',
    loggedToday: 'Logged today', noLogged: 'Nothing logged yet — tap an expected supplier or add one that arrived.',
    expected: 'Expected', received: 'Received', withIssue: 'Received · issue', awaiting: 'Awaiting', partial: 'Partial',
    items: 'items', dueBy: 'due',
    logTitle: 'Log delivery', supName: 'Supplier name', supNamePh: 'Type the supplier name', fromPO: 'From PO', cancel: 'Cancel',
    invoiceNo: 'Invoice number', dateTime: 'Date & time', auto: 'Auto',
    scanTitle: 'Scan invoice', scanCta: 'Scan invoice paper', scanHint: 'Photo or scan — purchasing enters the lines from it', scanned: 'Attached', rescan: 'Rescan', remove: 'Remove',
    scanCtaCloud: 'Add photo or PDF', scanHintCloud: 'Take a photo, or attach an image / PDF of the invoice', uploading: 'Uploading…', uploadFailed: 'Upload failed — please try again', viewScan: 'View scan',
    noteOptional: 'Note for purchasing (optional)', noteRequired: 'Note for purchasing (required)', notePh: 'What should purchasing check? e.g. short 2 boxes, no printed invoice, price looks high…',
    submitOk: 'Submit', submitIssue: 'Submit with issue',
    needName: 'Enter the supplier name to submit.', needInv: 'Add the invoice number, or use “Submit with issue” if there’s no invoice.', needScan: 'Scan the invoice, or use “Submit with issue”.', needNote: 'Describe the issue for purchasing to submit with issue.',
    noteFor: 'For purchasing:', noteFromPurchasing: 'Note from purchasing', handoff: '→ Sent to purchasing — they enter the product lines from the scanned invoice.',
    colTime: 'Time', colSupplier: 'Supplier', colInvoice: 'Invoice', colStatus: 'Status',
    summaryFoot: 'Product lines are entered by purchasing in the Supplier Invoice Pipeline. This screen only logs arrival, invoice and any issue.',
    okToast: 'Delivery submitted', issueToast: 'Submitted with issue — flagged to purchasing',
    todayLabel: 'Wednesday, 12 Aug 2026', datePrefix: '12 Aug 2026 · ',
    fromRequest: 'from a purchasing request', walkIn: 'walk-in / unscheduled supplier',
    // ported additions — product lines (Rule-7 entered unit + base) and the posting chain
    linesTitle: 'Product lines', addProduct: 'Add product', noProducts: 'No products for this supplier yet.',
    linesEmpty: 'No lines yet — add the products on this delivery, or submit and let purchasing enter them from the scan.',
    linesNoSupplier: 'Pick a known supplier to add product lines.', knownSuppliers: 'Known suppliers', newSupplierNote: 'New supplier — will be created on submit',
    qty: 'Qty', price: 'Price', per: 'per', vsLast: 'vs last', lastPrice: 'last', onHand: 'on hand', details: 'Details', hideDetails: 'Hide details',
    expiry: 'Expiry', batch: 'Batch', temp: 'Temperature', quality: 'Quality', qOk: 'OK', qIssue: 'Issue', rejected: 'Rejected', accepted: 'accepted',
    total: 'Total', enterQty: 'Enter quantity', enterPrice: 'Unit price', enterRejected: 'Rejected quantity', ordered: 'ordered',
    confirmTitle: 'Submit delivery?', confirmBody: 'Accepted quantities are posted to stock, moving-average costs update and the invoice enters the review pipeline.',
    linesPosted: 'lines posted', doneBody: 'Stock and moving-average costs are updated. The invoice is now in the review pipeline.', backToDeliveries: 'Back to deliveries',
    priceAlert: 'Price alert', noLines: 'no lines — purchasing enters them from the scan',
  },
  ar: {
    title: 'الاستلام', mk: 'المطبخ الرئيسي', userName: 'زياد', userRole: 'مخزن · مستلِم',
    tabDeliv: 'التوريدات', tabSummary: 'ملخص اليوم',
    expectedToday: 'متوقع اليوم', fromPurchasing: 'من طلبات المشتريات',
    arrivedTitle: 'وصل مورد — غير مدرج', arrivedSub: 'سجّل توريداً من مورد لم تجدوله المشتريات',
    loggedToday: 'مُسجل اليوم', noLogged: 'لا شيء بعد — انقر مورداً متوقعاً أو أضف مورداً وصل.',
    expected: 'متوقع', received: 'مُستلم', withIssue: 'مُستلم · ملاحظة', awaiting: 'بانتظار', partial: 'جزئي',
    items: 'أصناف', dueBy: 'الموعد',
    logTitle: 'تسجيل توريد', supName: 'اسم المورد', supNamePh: 'اكتب اسم المورد', fromPO: 'من أمر شراء', cancel: 'إلغاء',
    invoiceNo: 'رقم الفاتورة', dateTime: 'التاريخ والوقت', auto: 'تلقائي',
    scanTitle: 'مسح الفاتورة', scanCta: 'مسح ورقة الفاتورة', scanHint: 'صورة أو مسح — المشتريات تدخل الأسطر منه', scanned: 'مُرفق', rescan: 'إعادة المسح', remove: 'إزالة',
    scanCtaCloud: 'إضافة صورة أو PDF', scanHintCloud: 'التقط صورة، أو أرفق صورة / ملف PDF للفاتورة', uploading: 'جارٍ الرفع…', uploadFailed: 'فشل الرفع — يرجى المحاولة مرة أخرى', viewScan: 'عرض المسح',
    noteOptional: 'ملاحظة للمشتريات (اختياري)', noteRequired: 'ملاحظة للمشتريات (مطلوب)', notePh: 'ما الذي يجب أن تتحقق منه المشتريات؟ مثال: ناقص صندوقين، لا فاتورة مطبوعة…',
    submitOk: 'إرسال', submitIssue: 'إرسال مع ملاحظة',
    needName: 'أدخل اسم المورد للإرسال.', needInv: 'أضف رقم الفاتورة، أو استخدم «إرسال مع ملاحظة» إن لم توجد فاتورة.', needScan: 'امسح الفاتورة، أو استخدم «إرسال مع ملاحظة».', needNote: 'صف الملاحظة للمشتريات للإرسال مع ملاحظة.',
    noteFor: 'للمشتريات:', noteFromPurchasing: 'ملاحظة من المشتريات', handoff: '→ أُرسل للمشتريات — تدخل أسطر الأصناف من الفاتورة الممسوحة.',
    colTime: 'الوقت', colSupplier: 'المورد', colInvoice: 'الفاتورة', colStatus: 'الحالة',
    summaryFoot: 'أسطر الأصناف تدخلها المشتريات في خط فواتير الموردين. هذه الشاشة تسجّل الوصول والفاتورة وأي ملاحظة فقط.',
    okToast: 'تم إرسال التوريد', issueToast: 'أُرسل مع ملاحظة — نُبّهت المشتريات',
    todayLabel: 'الأربعاء ١٢ آب ٢٠٢٦', datePrefix: '١٢ آب ٢٠٢٦ · ',
    fromRequest: 'من طلب المشتريات', walkIn: 'مورد وصل غير مدرج',
    linesTitle: 'أسطر الأصناف', addProduct: 'إضافة صنف', noProducts: 'لا أصناف لهذا المورد بعد.',
    linesEmpty: 'لا أسطر بعد — أضف أصناف هذا التوريد، أو أرسل ودع المشتريات تدخلها من المسح.',
    linesNoSupplier: 'اختر مورداً معروفاً لإضافة أسطر الأصناف.', knownSuppliers: 'موردون معروفون', newSupplierNote: 'مورد جديد — سيُنشأ عند الإرسال',
    qty: 'الكمية', price: 'السعر', per: 'لكل', vsLast: 'مقارنة بآخر', lastPrice: 'آخر سعر', onHand: 'المتوفر', details: 'التفاصيل', hideDetails: 'إخفاء التفاصيل',
    expiry: 'الصلاحية', batch: 'الدفعة', temp: 'الحرارة', quality: 'الجودة', qOk: 'سليم', qIssue: 'مشكلة', rejected: 'مرفوض', accepted: 'مقبول',
    total: 'الإجمالي', enterQty: 'أدخل الكمية', enterPrice: 'سعر الوحدة', enterRejected: 'الكمية المرفوضة', ordered: 'مطلوب',
    confirmTitle: 'إرسال التوريد؟', confirmBody: 'تُرحّل الكميات المقبولة إلى المخزون، ويُحدّث متوسط الكلفة، وتدخل الفاتورة خط المراجعة.',
    linesPosted: 'أسطر مرحّلة', doneBody: 'تم تحديث المخزون ومتوسط الكلفة. الفاتورة الآن في خط المراجعة.', backToDeliveries: 'العودة إلى التوريدات',
    priceAlert: 'تنبيه سعر', noLines: 'بلا أسطر — المشتريات تدخلها من المسح',
  },
} as const;

export type StfText = typeof TEXT['en'];
