/** Accounting (lean, Part J) — TEXT dictionary. Prototype strings verbatim + keys needed by the store-backed port. */
export const TEXT = {
  en: {
    title: 'Accounting',
    feedsNote: 'KIS feeds the accountant — no ledger here',
    tabs: { cash: 'Cash handover', fx: 'Daily rate', sales: 'Daily sales', bills: 'Supplier bills', exp: 'Expenses' },
    cashInHand: 'Central cash-in-hand', cashNote: 'Pays expenses & supplier bills. Fed by confirmed handovers.',
    inTransit: 'In transit from branches', openGaps: 'Open handover gaps', gapSub: 'declared ≠ confirmed',
    cashHint: 'Branch closings awaiting receipt. Confirm what actually arrived — the declared-vs-confirmed gap is the control point (same pattern as stock transfers).',
    declaredRow: 'Declared', confirmedRow: 'Confirmed', rateAt: 'rate',
    confirmHint: 'Count what arrived, then confirm. Confirming feeds central cash-in-hand.',
    confirmFull: 'Confirm — matches declared', confirmWithGap: 'Confirm with gap…',
    pendingSt: 'In transit', confirmedSt: 'Confirmed ✓', gapSt: 'Gap flagged',
    cashFoot: 'Every confirmation is audit-logged (E4). Gaps escalate to management and the owner report.',
    todayRate: 'Today’s USD/LBP rate', setBy: 'Set by Nadia (accountant) at 08:02', appliedTo: 'applied to', closingsWord: 'closings so far',
    setRate: 'Set today’s rate', fxLockNote: 'One rate per day — closings lock to the rate in force.',
    rateHistory: 'Rate history', fxFoot: 'Rates are audit-logged. Closings stamp the rate at their date — history never restates.',
    exportAcct: 'Export for accountant', location: 'Location', total: 'Total', food: 'Food', beverage: 'Beverage', tobacco: 'Tobacco', tax: 'Tax',
    salesFoot: 'Sourced live from POS day-close (Part G). Main Kitchen has no direct sales.',
    mixTitle: 'Category mix — combined', mixFoot: 'Feeds the financial P&L revenue lines (value + %).',
    totalOwed: 'Total owed', overdue: 'Overdue', dueWeek: 'Due this week', byCurrency: 'By currency',
    billsHint: 'Sourced from the three-role invoicing pipeline (ACC-INV-01) — the accountant’s step there creates the payable here. No second inbox.',
    openPipeline: 'Open pipeline (ACC-INV-01)',
    supplier: 'Supplier', invoice: 'Invoice', due: 'Due', amount: 'Amount', linkedRcv: 'Receiving', status: 'Status',
    recordPayment: 'Record payment', open: 'Open', partial: 'Partial', paidSt: 'Paid ✓', overdueSt: 'Overdue',
    billsFoot: 'Payments reduce central cash-in-hand (Cash handover tab). LBP bills convert at the day rate.',
    expHint: 'Categorized, paid from central cash, allocated to one location or split evenly across three. Accrual month ≠ pay date.',
    addExpense: 'Add expense', expense: 'Expense', category: 'Category', allocation: 'Allocation', accrualMonth: 'Belongs to', paid: 'Paid',
    recurring: 'RECURRING', lateNote: 'paid after month end', expFoot: 'Salaries flow from payroll. Late-landing costs keep their month provisional in the financial P&L (owner view).',
    cancel: 'Cancel',
    payTitle: 'Record payment', payBody: 'Pays from central cash-in-hand. LBP converts at today’s rate (90,000). Logged and exported to the accountant.',
    payWarn: 'Cash-in-hand decreases now; the bill moves to Paid.', payCta: 'Pay from central cash',
    gapTitle: 'Confirm with gap', gapBody: 'Enter what actually arrived. The difference stays flagged as a handover gap and escalates to management.',
    gapWarn: 'The gap is the control point — it does not disappear by confirming.', gapCta: 'Confirm — flag gap',
    expTitle: 'Add expense', expBody: 'Category, amount, allocation, and the month it BELONGS to (accrual) — separate from the pay date.',
    expPh1: 'Expense — e.g. Electricity · Rock', expPh2: 'Amount USD + accrual month — e.g. 480 · Aug 2026',
    expWarn: 'An August expense paid in September belongs to August — it keeps August provisional until it lands.',
    expCta: 'Save expense', allocRock: 'Rock', allocKad: 'Kaddoum', allocMk: 'Main Kitchen', allocSplit: 'Split evenly ÷3',
    fxToast: 'Rate set — applies to today’s closings', exportToast: 'Export queued — accountant handoff',
    payToast: 'Paid from central cash — logged', confirmToast: 'Confirmed — cash-in-hand updated', gapToast: 'Confirmed with gap — flagged',
    expToast: 'Expense saved — allocated',
    // ── keys added for the store-backed port ──
    gapPh1: 'Confirmed arrived — e.g. $595.50', gapPh1Lbp: 'Confirmed arrived — e.g. 58,500,000', gapPh2: 'Gap note (required)',
    confirmedArrived: 'Confirmed arrived', declaredTotal: 'Declared total', confirmedTotal: 'Confirmed total', difference: 'Difference',
    withinTol: 'within tolerance', beyondTol: 'beyond tolerance',
    shifts: { Evening: 'evening', Morning: 'morning', 'Full day': 'full day' } as Record<string, string>,
    closingsUnit: 'closings', noClosings: 'No closings in this scope.',
    setByWho: 'Set by', roleAccountant: 'accountant', roleOwner: 'owner',
    dayView: 'Day', mtdView: 'Month to date', combined: 'Combined', noSales: 'No day-close yet for this date.', drillHint: 'Click a day’s row to open its cash handover',
    noBills: 'No bills in this scope.', overdueNote: 'overdue', lbpAtRate: 'LBP at day rate',
    allMonths: 'All months', noExpenses: 'No expenses in this scope.',
    editTitle: 'Edit expense', editCta: 'Save changes', editToast: 'Expense updated — logged',
    fVendor: 'Vendor / description', fAmount: 'Amount', fCurrency: 'Currency', fCategory: 'Category', fAccrual: 'Belongs to (accrual month)', fPayDate: 'Pay date', fMethod: 'Payment method', fAlloc: 'Allocation', fRecurring: 'Recurring (e.g. rent)',
    methods: { cash: 'Cash', card: 'Card', whish: 'Whish' },
    cats: { rent: 'Rent', gas: 'Gas', electricity: 'Electricity', maintenance: 'Maint.', uniforms: 'Uniforms', marketing: 'Marketing', salaries: 'Salaries', tax: 'Tax', other: 'Other' },
    catsLong: { rent: 'Rent', gas: 'Gas', electricity: 'Electricity', maintenance: 'Maintenance', uniforms: 'Uniforms', marketing: 'Marketing', salaries: 'Salaries', tax: 'Tax', other: 'Other' },
    payMethod: 'Payment method',
  },
  ar: {
    title: 'المحاسبة',
    feedsNote: 'KIS يغذّي المحاسب — لا دفتر أستاذ هنا',
    tabs: { cash: 'تسليم النقد', fx: 'سعر اليوم', sales: 'المبيعات اليومية', bills: 'فواتير الموردين', exp: 'المصاريف' },
    cashInHand: 'النقد المركزي المتوفر', cashNote: 'يدفع المصاريف وفواتير الموردين. يتغذى من التسليمات المؤكدة.',
    inTransit: 'في الطريق من الفروع', openGaps: 'فجوات تسليم مفتوحة', gapSub: 'المعلن ≠ المؤكد',
    cashHint: 'إقفالات الفروع بانتظار الاستلام. أكّد ما وصل فعلاً — فجوة المعلن مقابل المؤكد هي نقطة الضبط (نفس نمط تحويلات المخزون).',
    declaredRow: 'المعلن', confirmedRow: 'المؤكد', rateAt: 'السعر',
    confirmHint: 'عُدّ ما وصل ثم أكّد. التأكيد يغذي النقد المركزي.',
    confirmFull: 'تأكيد — مطابق للمعلن', confirmWithGap: 'تأكيد مع فجوة…',
    pendingSt: 'في الطريق', confirmedSt: 'مؤكد ✓', gapSt: 'فجوة معلّمة',
    cashFoot: 'كل تأكيد يُسجل بالتدقيق (E4). الفجوات تتصاعد إلى الإدارة وتقرير المالك.',
    todayRate: 'سعر الدولار/الليرة اليوم', setBy: 'حددته ناديا (المحاسبة) في ٠٨:٠٢', appliedTo: 'طُبق على', closingsWord: 'إقفالات حتى الآن',
    setRate: 'تحديد سعر اليوم', fxLockNote: 'سعر واحد يومياً — الإقفالات ترتبط بالسعر الساري.',
    rateHistory: 'سجل الأسعار', fxFoot: 'الأسعار تُسجل بالتدقيق. الإقفالات تثبّت سعر تاريخها — التاريخ لا يُعاد.',
    exportAcct: 'تصدير للمحاسب', location: 'الموقع', total: 'الإجمالي', food: 'طعام', beverage: 'مشروبات', tobacco: 'تبغ', tax: 'ضريبة',
    salesFoot: 'من إقفال يوم POS مباشرة (الجزء G). المطبخ الرئيسي بلا مبيعات مباشرة.',
    mixTitle: 'مزيج الفئات — مجمّع', mixFoot: 'يغذي بنود إيرادات الأرباح والخسائر المالية (قيمة + ٪).',
    totalOwed: 'إجمالي المستحق', overdue: 'متأخر', dueWeek: 'مستحق هذا الأسبوع', byCurrency: 'حسب العملة',
    billsHint: 'من خط الفوترة ثلاثي الأدوار (ACC-INV-01) — خطوة المحاسب هناك تنشئ المستحق هنا. لا صندوق وارد ثانٍ.',
    openPipeline: 'فتح الخط (ACC-INV-01)',
    supplier: 'المورد', invoice: 'الفاتورة', due: 'الاستحقاق', amount: 'المبلغ', linkedRcv: 'الاستلام', status: 'الحالة',
    recordPayment: 'تسجيل دفعة', open: 'مفتوحة', partial: 'جزئية', paidSt: 'مدفوعة ✓', overdueSt: 'متأخرة',
    billsFoot: 'الدفعات تخفض النقد المركزي (تبويب تسليم النقد). فواتير الليرة تُحوَّل بسعر اليوم.',
    expHint: 'مصنّفة، تُدفع من النقد المركزي، تُخصص لموقع واحد أو تُقسم بالتساوي على الثلاثة. شهر الاستحقاق ≠ تاريخ الدفع.',
    addExpense: 'إضافة مصروف', expense: 'المصروف', category: 'الفئة', allocation: 'التخصيص', accrualMonth: 'يخص شهر', paid: 'الدفع',
    recurring: 'دوري', lateNote: 'دُفع بعد نهاية الشهر', expFoot: 'الرواتب من كشف الرواتب. التكاليف المتأخرة تُبقي شهرها مؤقتاً في الأرباح والخسائر المالية (عرض المالك).',
    cancel: 'إلغاء',
    payTitle: 'تسجيل دفعة', payBody: 'تُدفع من النقد المركزي. الليرة تُحوَّل بسعر اليوم (90,000). تُسجل وتُصدَّر للمحاسب.',
    payWarn: 'النقد المتوفر ينخفض الآن؛ الفاتورة تصبح مدفوعة.', payCta: 'الدفع من النقد المركزي',
    gapTitle: 'تأكيد مع فجوة', gapBody: 'أدخل ما وصل فعلاً. الفرق يبقى معلّماً كفجوة تسليم ويتصاعد للإدارة.',
    gapWarn: 'الفجوة هي نقطة الضبط — لا تختفي بالتأكيد.', gapCta: 'تأكيد — تعليم الفجوة',
    expTitle: 'إضافة مصروف', expBody: 'الفئة والمبلغ والتخصيص والشهر الذي يخصه (الاستحقاق) — منفصل عن تاريخ الدفع.',
    expPh1: 'المصروف — مثال: كهرباء · روك', expPh2: 'المبلغ بالدولار + شهر الاستحقاق — مثال: 480 · آب 2026',
    expWarn: 'مصروف آب المدفوع في أيلول يخص آب — ويُبقي آب مؤقتاً حتى يصل.',
    expCta: 'حفظ المصروف', allocRock: 'روك', allocKad: 'قدّوم', allocMk: 'المطبخ الرئيسي', allocSplit: 'قسمة بالتساوي ÷٣',
    fxToast: 'حُدد السعر — يسري على إقفالات اليوم', exportToast: 'التصدير في الطابور — تسليم المحاسب',
    payToast: 'دُفعت من النقد المركزي — سُجلت', confirmToast: 'أُكد — تحدّث النقد المتوفر', gapToast: 'أُكد مع فجوة — عُلّمت',
    expToast: 'حُفظ المصروف — خُصص',
    // ── keys added for the store-backed port ──
    gapPh1: 'المؤكد وصوله — مثال: $595.50', gapPh1Lbp: 'المؤكد وصوله — مثال: 58,500,000', gapPh2: 'ملاحظة الفجوة (إلزامي)',
    confirmedArrived: 'المؤكد وصوله', declaredTotal: 'إجمالي المعلن', confirmedTotal: 'إجمالي المؤكد', difference: 'الفرق',
    withinTol: 'ضمن الحد المسموح', beyondTol: 'خارج الحد المسموح',
    shifts: { Evening: 'مساء', Morning: 'صباح', 'Full day': 'يوم كامل' } as Record<string, string>,
    closingsUnit: 'إقفالات', noClosings: 'لا إقفالات في هذا النطاق.',
    setByWho: 'حدده', roleAccountant: 'المحاسب', roleOwner: 'المالك',
    dayView: 'يوم', mtdView: 'الشهر حتى تاريخه', combined: 'المجمّع', noSales: 'لا إقفال يوم بعد لهذا التاريخ.', drillHint: 'انقر صف اليوم لفتح تسليم النقد الخاص به',
    noBills: 'لا فواتير في هذا النطاق.', overdueNote: 'متأخرة', lbpAtRate: 'الليرة بسعر اليوم',
    allMonths: 'كل الأشهر', noExpenses: 'لا مصاريف في هذا النطاق.',
    editTitle: 'تعديل مصروف', editCta: 'حفظ التعديلات', editToast: 'حُدّث المصروف — سُجل',
    fVendor: 'المورد / الوصف', fAmount: 'المبلغ', fCurrency: 'العملة', fCategory: 'الفئة', fAccrual: 'يخص شهر (الاستحقاق)', fPayDate: 'تاريخ الدفع', fMethod: 'طريقة الدفع', fAlloc: 'التخصيص', fRecurring: 'دوري (مثل الإيجار)',
    methods: { cash: 'نقد', card: 'بطاقة', whish: 'Whish' },
    cats: { rent: 'إيجار', gas: 'غاز', electricity: 'كهرباء', maintenance: 'صيانة', uniforms: 'زي موحد', marketing: 'تسويق', salaries: 'رواتب', tax: 'ضريبة', other: 'أخرى' },
    catsLong: { rent: 'إيجار', gas: 'غاز', electricity: 'كهرباء', maintenance: 'صيانة', uniforms: 'زي موحد', marketing: 'تسويق', salaries: 'رواتب', tax: 'ضريبة', other: 'أخرى' },
    payMethod: 'طريقة الدفع',
  },
};

export type AccText = typeof TEXT.en;
