/** General Ledger (Release 2 proposal) — TEXT dictionary, verbatim from the prototype. */
export const TEXT = {
  en: {
    title: 'Accounting · General Ledger', r2: 'RELEASE 2 · PROPOSED',
    proposalNote: 'Proposal — today KIS feeds the accountant’s own software (per the accounting interview). This ledger is what Release 2 would look like if the books move in-house: entries auto-post from events KIS already records.',
    tabJournal: 'Journal', tabCoa: 'Chart of accounts', tabTb: 'Trial balance',
    balanced: 'BALANCED', manualJe: 'Manual entry', jShowing: 'entries · Aug 2026',
    journalNote: 'System entries post automatically from the operational modules — POS day close, supplier-invoice approval (ACC-INV-01), waste approval, cash handover (ACC-CLS-02), and the HR payroll close (HR-PAY-01). Manual entries require Super Admin and are audit-logged.',
    coaNote: 'Click any account to see its journal entries. Codes follow a lean 4-digit scheme; per-location sub-accounts keep the P&L per branch.',
    tbBalancedMsg: 'Trial balance is in balance — debits equal credits for Aug 2026 (24 entries).',
    tbCode: 'Code', tbAcct: 'Account', tbDr: 'Debit', tbCr: 'Credit', tbTotals: 'Totals', tbExcel: 'Excel ↓', tbExportAcct: 'Export for accountant ↓',
    tbNote: 'Same export the accountant gets today — the ledger just makes it self-auditing.',
    mMemo: 'Memo — e.g. Owner capital injection', mDebit: 'Debit account', mCredit: 'Credit account', mAmount: 'Amount', mPost: 'Post entry', cancel: 'Cancel',
    mBalanced: '✓ Entry balances — 1 debit line, 1 credit line', mSame: '▲ Debit and credit account must differ', mNoAmt: 'Enter an amount to post',
    posted: 'Posted — appears at the top of the journal, source MANUAL', exported: 'Export queued',
    srcAll: 'All sources',
    origins: { POS: 'Auto-posted from POS day close', AP: 'Auto-posted from invoice approval', WASTE: 'Auto-posted from waste approval', CASH: 'Auto-posted from cash handover', HR: 'Auto-posted from payroll period close', BANK: 'Auto-posted from payment run', MANUAL: 'Manual entry · Super Admin · audit-logged' },
    groups: { assets: 'Assets', liab: 'Liabilities', equity: 'Equity', rev: 'Revenue', exp: 'Expenses' },
    period: 'Aug 2026',
  },
  ar: {
    title: 'المحاسبة · دفتر الأستاذ العام', r2: 'إصدار ٢ · مقترح',
    proposalNote: 'مقترح — حالياً يغذي KIS برنامج المحاسب (بحسب مقابلة المحاسبة). هذا الدفتر هو شكل الإصدار الثاني إذا انتقلت الدفاتر إلى الداخل: القيود تُرحَّل تلقائياً من أحداث يسجلها KIS أصلاً.',
    tabJournal: 'اليومية', tabCoa: 'دليل الحسابات', tabTb: 'ميزان المراجعة',
    balanced: 'متوازن', manualJe: 'قيد يدوي', jShowing: 'قيداً · آب 2026',
    journalNote: 'تُرحَّل القيود تلقائياً من الوحدات التشغيلية — إقفال POS، اعتماد فواتير الموردين، اعتماد الهدر، تسليم النقد، وإقفال رواتب HR. القيود اليدوية تتطلب مشرفاً عاماً وتُسجَّل في التدقيق.',
    coaNote: 'انقر أي حساب لعرض قيوده. الترميز رباعي بسيط؛ حسابات فرعية لكل موقع تحفظ أرباح كل فرع.',
    tbBalancedMsg: 'ميزان المراجعة متوازن — المدين يساوي الدائن لآب 2026 (٢٤ قيداً).',
    tbCode: 'الرمز', tbAcct: 'الحساب', tbDr: 'مدين', tbCr: 'دائن', tbTotals: 'الإجمالي', tbExcel: 'إكسل ↓', tbExportAcct: 'تصدير للمحاسب ↓',
    tbNote: 'نفس التصدير الذي يستلمه المحاسب اليوم — الدفتر يجعله ذاتي التدقيق.',
    mMemo: 'البيان — مثال: ضخ رأسمال من المالك', mDebit: 'الحساب المدين', mCredit: 'الحساب الدائن', mAmount: 'المبلغ', mPost: 'ترحيل القيد', cancel: 'إلغاء',
    mBalanced: '✓ القيد متوازن — سطر مدين وسطر دائن', mSame: '▲ يجب أن يختلف الحسابان', mNoAmt: 'أدخل مبلغاً للترحيل',
    posted: 'رُحّل — يظهر أعلى اليومية، المصدر يدوي', exported: 'أُدرج التصدير',
    srcAll: 'كل المصادر',
    origins: { POS: 'ترحيل تلقائي من إقفال POS', AP: 'ترحيل تلقائي من اعتماد الفاتورة', WASTE: 'ترحيل تلقائي من اعتماد الهدر', CASH: 'ترحيل تلقائي من تسليم النقد', HR: 'ترحيل تلقائي من إقفال الرواتب', BANK: 'ترحيل تلقائي من دفعة بنكية', MANUAL: 'قيد يدوي · مشرف عام · مسجَّل في التدقيق' },
    groups: { assets: 'الأصول', liab: 'الالتزامات', equity: 'حقوق الملكية', rev: 'الإيرادات', exp: 'المصاريف' },
    period: 'آب 2026',
  },
};
