/** TEXT dictionary — copied verbatim from "KIS Variance Investigation.dc.html" (+ keys for strings the prototype kept inline). */
const EN = {
  title: 'Variance investigation', openCases: 'Open investigations', qtyVar: 'Qty variance', costImpact: 'Cost impact',
  unfavorable: 'Unfavorable', reconciliation: 'Reconciliation', confirmedData: 'confirmed data',
  varLine: 'Expected vs physical', evidence: 'Evidence checklist',
  possibleCauses: 'Possible causes', unconfirmed: 'not confirmed',
  noAiNote: 'Listed for the investigator — no automated inference. The AI analysis layer (B9) activates in a later release.',
  notes: 'Notes & corrective actions', notePh: 'Log a note or corrective action…', add: 'Add',
  accept: 'Accept variance', acceptedBtn: 'Accepted ✓', resolvedBadge: 'Resolved', recount: 'Trigger recount',
  acceptTitle: 'Accept variance', acceptBody: 'Accepting writes off −$15.84 at moving-average cost to this location’s P&L. Requires approval; fully logged.',
  acceptWarn: 'The evidence checklist and notes are stored with the acceptance for audit.',
  acceptCta: 'Request approval', cancel: 'Cancel',
  acceptedToast: 'Acceptance sent for approval', recountToast: 'Recount task created for tomorrow 08:00',
  correct: 'Correct count', correctTitle: 'Count correction',
  correctBody: 'Staff counted this item incorrectly. Enter the adjusted physical count confirmed during the investigation. The system recomputes the variance and writes the correction to the audit log.',
  staffCounted: 'Staff counted', correctField: 'Adjusted physical count', correctByLabel: 'Authorized by',
  reasonLabel: 'Reason for correction', reasonWrong: 'Wrong count — staff did not count correctly', reasonWaste: 'Unrecorded waste — staff did not punch it',
  correctNoteLabel: 'Note', optional: '(optional)', correctNotePh: 'Add detail for the audit log…',
  signedIn: 'signed in', authorized: 'Authorized',
  viewSheet: 'View count sheet', sheetTitle: 'Physical count sheet', submitted: 'Submitted',
  itemCol: 'Item', countedCol: 'Counted', close: 'Close', countedByWord: 'Counted by',
  correctWarn: 'The original staff count is retained. The adjustment is logged with the authorizing role and timestamp for audit.',
  correctCta: 'Save correction',
  correctedTo: 'Count corrected to', correctedSuffix: 'adjusted after investigation',
  correctToast: 'Count corrected · logged to audit', correctToastWaste: 'Corrected · waste entry auto-posted',
  found: 'Found', none: 'None found', normal: 'Normal',
  locs: { mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' },
  // ── inline strings from the prototype logic ──
  you: 'You', underInvestigation: 'Item under investigation', countAdjustment: '(count adjustment)',
  wasteAutoPosted: 'Waste entry auto-posted', ownerRole: 'Owner · Superuser', stockCard: 'Stock card',
  noInvestigation: 'No open investigation for this item',
  wasteInfoAmount: (w: string, unit: string, loc: string) => `The system auto-creates a waste entry of ${w} ${unit} for ${loc}. The count enters stock at the adjusted figure; the shortfall posts as waste — not a P&L write-off.`,
  wasteInfoGeneric: 'Once you enter the adjusted count, the system auto-posts the shortfall as a waste entry instead of a P&L write-off.',
};

export type VarText = typeof EN;

export const TEXT: Record<'en' | 'ar', VarText> = {
  en: EN,
  ar: {
    title: 'تحقيق الفروقات', openCases: 'تحقيقات مفتوحة', qtyVar: 'فرق الكمية', costImpact: 'أثر الكلفة',
    unfavorable: 'سلبي', reconciliation: 'المطابقة', confirmedData: 'بيانات مؤكدة',
    varLine: 'المتوقع مقابل الفعلي', evidence: 'قائمة الأدلة',
    possibleCauses: 'أسباب محتملة', unconfirmed: 'غير مؤكدة',
    noAiNote: 'مدرجة للمحقق — لا استنتاج آلي. طبقة التحليل الذكي (B9) تُفعّل في إصدار لاحق.',
    notes: 'ملاحظات وإجراءات تصحيحية', notePh: 'سجّل ملاحظة أو إجراءً تصحيحياً…', add: 'إضافة',
    accept: 'قبول الفرق', acceptedBtn: 'مقبول ✓', resolvedBadge: 'محلول', recount: 'إعادة الجرد',
    acceptTitle: 'قبول الفرق', acceptBody: 'القبول يشطب −١٥٫٨٤$ بمتوسط الكلفة إلى أرباح وخسائر هذا الموقع. يتطلب موافقة ويُسجل بالكامل.',
    acceptWarn: 'تُحفظ قائمة الأدلة والملاحظات مع القبول للتدقيق.',
    acceptCta: 'طلب موافقة', cancel: 'إلغاء',
    acceptedToast: 'أُرسل القبول للموافقة', recountToast: 'أُنشئت مهمة إعادة جرد غداً ٠٨:٠٠',
    correct: 'تصحيح الجرد', correctTitle: 'تصحيح الجرد',
    correctBody: 'قام الموظف بعدّ هذا الصنف بشكل خاطئ. أدخل الجرد الفعلي المعدّل المؤكد خلال التحقيق. يعيد النظام احتساب الفرق ويسجل التصحيح في سجل التدقيق.',
    staffCounted: 'عدّ الموظف', correctField: 'الجرد الفعلي المعدّل', correctByLabel: 'باعتماد من',
    reasonLabel: 'سبب التصحيح', reasonWrong: 'جرد خاطئ — الموظف لم يعدّ بشكل صحيح', reasonWaste: 'هدر غير مسجّل — الموظف لم يُدخله',
    correctNoteLabel: 'ملاحظة', optional: '(اختياري)', correctNotePh: 'أضف تفاصيل لسجل التدقيق…',
    signedIn: 'مُسجّل الدخول', authorized: 'مُخوّل',
    viewSheet: 'عرض ورقة الجرد', sheetTitle: 'ورقة الجرد الفعلي', submitted: 'مُرسلة',
    itemCol: 'الصنف', countedCol: 'المعدود', close: 'إغلاق', countedByWord: 'عدّه',
    correctWarn: 'يُحتفظ بعدّ الموظف الأصلي. يُسجّل التعديل مع الدور المعتمِد والوقت للتدقيق.',
    correctCta: 'حفظ التصحيح',
    correctedTo: 'صُحّح الجرد إلى', correctedSuffix: 'تعديل بعد التحقيق',
    correctToast: 'تم تصحيح الجرد · سُجّل في التدقيق', correctToastWaste: 'تم التصحيح · سُجّل هدر تلقائياً',
    found: 'موجود', none: 'لا يوجد', normal: 'طبيعي',
    locs: { mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' },
    you: 'أنت', underInvestigation: 'الصنف قيد التحقيق', countAdjustment: '(تعديل جرد)',
    wasteAutoPosted: 'تم إنشاء قيد هدر', ownerRole: 'المالك · مشرف', stockCard: 'بطاقة المخزون',
    noInvestigation: 'لا يوجد تحقيق مفتوح لهذا الصنف',
    wasteInfoAmount: (w, unit, loc) => `يُنشئ النظام قيد هدر تلقائياً بمقدار ${w} ${unit} لـ${loc}. يدخل الجرد المخزون بالرقم المعدّل، ويُسجّل النقص كهدر وليس شطباً على الأرباح والخسائر.`,
    wasteInfoGeneric: 'عند إدخال الجرد المعدّل، يُنشئ النظام قيد هدر تلقائياً بالفرق بدل شطبه على الأرباح والخسائر.',
  },
};
