/** STF-PRD-00/02/03/04 (revised) — TEXT dictionary, prototype strings verbatim + inline strings lifted into keys. */
const EN = {
  plansHub: 'Plans', mk: 'Main Kitchen', user: 'Rami · Prep',
  hubTitle: 'Production plans — today', hubHint: 'Your assigned plans. Open any plan; switching keeps each plan’s state.',
  hubNote: 'Plans stay independent — pause one, work another. Offline: all plan state is queued.',
  planned: 'planned', notStarted: 'Not started', inProgress: 'In progress', paused: 'Paused', doneSt: 'Done ✓',
  gapBadge: 'Open gap', stageAt: 'At:',
  startTitle: 'Start batch', plannedQty: 'Planned quantity', autoId: 'auto',
  recommended: 'Recommended — from recipe × plan', recRawLabel: 'net raw needed', recSecLabel: 'marinade needed',
  inputMode: 'Raw input mode', commitExact: 'Commit exact', commitSub: 'Enter only what you’ll actually use.',
  drawReturn: 'Draw & return', drawSub: 'Enter what you draw now; return the leftover at the end.',
  trimWaste: 'Trimming waste', trimNote: 'After trimming — routes to Waste (D3)',
  saveLater: 'Save & back', startBatch: 'Start batch',
  absurd: 'That’s far above the recommended amount — confirm this is right before starting.',
  stagesTitle: 'Stages', marinationStep: 'Marination — computed from chicken in use',
  chickenInUse: 'Working quantity (net)', marinadeNeeded: 'Marinade needed (recipe)', marinadeActual: 'Actual used — tap',
  stageWaste: '⌫ Record stage waste → D3', pauseSwitch: 'Pause & switch plan', toOutput: 'To output →',
  outputTitle: 'Output & reconcile', outCount: 'produced — count', outUnitNote: 'The transfer + count unit (STF-TRF, counts)',
  leftoverReturn: 'Leftover returned', leftoverNote: 'Back to the fridge — arithmetic, not a stock movement',
  actualUsed: 'Actual used', reconcile: 'Reconciliation — recipe standard vs actual',
  recipeStandard: 'Recipe standard', gapWeight: 'weight', gapPct: 'vs recipe', gapCost: 'cost leak',
  returnPromptQ: 'Large gap — did you return raw to the fridge without logging it?',
  returnPromptYes: 'Yes — enter the return', returnPromptNo: 'No — the gap is real',
  gapFlagNote: 'The gap is flagged to you, the kitchen manager (MGT-PRD-06), and cost. Drawn-vs-returned is bookkeeping, not variance.',
  completeBatch: 'Complete batch', backToPlans: 'Back to plans',
  doneTitle: 'Batch completed', cancel: 'Cancel', done: 'Done',
  wasteToast: 'Stage waste — opens D3 entry', savedToast: 'Saved — plan paused',
  steps: 'Steps',
  // ── inline strings from the prototype logic, lifted into keys ──
  outputStage: 'output & reconcile', completedWord: 'Completed', tapWhenDone: 'Tap when done', neededPrefix: 'Needed: ',
  planDrawn: (raw: string) => `(plan — drawn ${raw} resolves on return)`,
  provisional: 'vs recipe — provisional until leftover is returned', recorded: 'vs recipe — recorded to cost',
  commitDeriv: 'commit exact − trim', trimWord: 'trim', ruleBase: 'KG base · Rule 7',
  entersStock: 'enters stock at built-up cost', gapWord: 'Gap ', sentToReview: 'sent to gap review (MGT-PRD-06)',
  // ── additions for the store-backed port ──
  noPlans: 'No published plans for today.',
  confirmBody: 'Posts the raw and marinade out of stock, the output in at built-up cost, and records the gap for review. Trimming waste goes to Waste.',
  startedToast: 'Batch started —',
  roles: { storekeeper: 'Storekeeper', prep: 'Prep', production: 'Production', service: 'Service', manager: 'Manager', owner: 'Owner' } as Record<string, string>,
};

export type Text = typeof EN;

export const TEXT: Record<'en' | 'ar', Text> = {
  en: EN,
  ar: {
    plansHub: 'الخطط', mk: 'المطبخ الرئيسي', user: 'رامي · تحضير',
    hubTitle: 'خطط الإنتاج — اليوم', hubHint: 'خططك المسندة. افتح أي خطة؛ التبديل يحفظ حالة كل خطة.',
    hubNote: 'الخطط مستقلة — أوقف واحدة واعمل على أخرى. دون اتصال: كل الحالات في الطابور.',
    planned: 'مخطط', notStarted: 'لم تبدأ', inProgress: 'قيد التنفيذ', paused: 'موقوفة', doneSt: 'تمت ✓',
    gapBadge: 'فجوة مفتوحة', stageAt: 'عند:',
    startTitle: 'بدء الدفعة', plannedQty: 'الكمية المخططة', autoId: 'تلقائي',
    recommended: 'الموصى به — وصفة × خطة', recRawLabel: 'الخام الصافي المطلوب', recSecLabel: 'التتبيلة المطلوبة',
    inputMode: 'طريقة إدخال الخام', commitExact: 'التزام دقيق', commitSub: 'أدخل فقط ما ستستخدمه فعلاً.',
    drawReturn: 'سحب وإرجاع', drawSub: 'أدخل ما تسحبه الآن؛ أعد المتبقي في النهاية.',
    trimWaste: 'هدر التشفية', trimNote: 'بعد التشفية — يُحوّل إلى الهدر (D3)',
    saveLater: 'حفظ ورجوع', startBatch: 'بدء الدفعة',
    absurd: 'الكمية أعلى بكثير من الموصى به — أكّد أنها صحيحة قبل البدء.',
    stagesTitle: 'المراحل', marinationStep: 'التتبيل — محسوب من الدجاج المستخدم',
    chickenInUse: 'كمية العمل (صافٍ)', marinadeNeeded: 'التتبيلة المطلوبة (وصفة)', marinadeActual: 'المستخدم فعلاً — انقر',
    stageWaste: '⌫ تسجيل هدر مرحلة ← D3', pauseSwitch: 'إيقاف وتبديل الخطة', toOutput: 'إلى الإنتاج ←',
    outputTitle: 'الإنتاج والمطابقة', outCount: 'المنتج — عدّاً', outUnitNote: 'وحدة التحويل والجرد (STF-TRF، الجرد)',
    leftoverReturn: 'المتبقي المعاد', leftoverNote: 'إلى البراد — عملية حسابية لا حركة مخزون',
    actualUsed: 'المستخدم فعلاً', reconcile: 'المطابقة — معيار الوصفة مقابل الفعلي',
    recipeStandard: 'معيار الوصفة', gapWeight: 'الوزن', gapPct: 'عن الوصفة', gapCost: 'تسرب الكلفة',
    returnPromptQ: 'فجوة كبيرة — هل أعدت خاماً إلى البراد دون تسجيله؟',
    returnPromptYes: 'نعم — أدخل المعاد', returnPromptNo: 'لا — الفجوة حقيقية',
    gapFlagNote: 'تُبلّغ الفجوة لك ولمدير المطبخ (MGT-PRD-06) وللكلفة. المسحوب مقابل المعاد حسابات لا فروقات.',
    completeBatch: 'إنهاء الدفعة', backToPlans: 'عودة إلى الخطط',
    doneTitle: 'اكتملت الدفعة', cancel: 'إلغاء', done: 'تم',
    wasteToast: 'هدر مرحلة — يفتح إدخال D3', savedToast: 'حُفظ — الخطة موقوفة',
    steps: 'الخطوات',
    outputStage: 'الإنتاج والمطابقة', completedWord: 'مكتمل', tapWhenDone: 'انقر عند الإنجاز', neededPrefix: 'المطلوب: ',
    planDrawn: (raw: string) => `(المخطط — المسحوب ${raw} يُحسم عند الإرجاع)`,
    provisional: 'عن الوصفة — مؤقت حتى إرجاع المتبقي', recorded: 'عن الوصفة — يُسجل للكلفة',
    commitDeriv: 'التزام دقيق − التشفية', trimWord: 'تشفية', ruleBase: 'كغ أساس · القاعدة ٧',
    entersStock: 'يدخل المخزون بالكلفة المتراكمة', gapWord: 'الفجوة ', sentToReview: 'مُرسلة إلى مراجعة الفجوات (MGT-PRD-06)',
    noPlans: 'لا خطط منشورة لليوم.',
    confirmBody: 'يرحّل الخام والتتبيلة من المخزون، ويدخل الناتج بالكلفة المتراكمة، ويسجل الفجوة للمراجعة. هدر التشفية يذهب إلى الهدر.',
    startedToast: 'بدأت الدفعة —',
    roles: { storekeeper: 'أمين مستودع', prep: 'تحضير', production: 'إنتاج', service: 'خدمة', manager: 'مدير', owner: 'مالك' },
  },
};
