/** Financial P&L (owner) — TEXT dictionary. Prototype strings verbatim + keys needed by the store-backed port. */
export const TEXT = {
  en: {
    pnlTab: 'Financial P&L', accessTab: 'Access grants', ownerOnly: 'OWNER ONLY',
    value: 'Value', pctOfSales: '% of sales', exportAcct: 'Export to accountant',
    provisional: 'PROVISIONAL', finalSt: 'FINAL · LOCKED',
    provText: 'Operational numbers are in, but late costs that BELONG to this month are still pending. The month stays open until they land.',
    finalText: 'All late costs landed and reconciled. The month is locked — accrual-complete.',
    markFinal: 'Reconcile & mark Final…', pendingChip: 'PENDING',
    waitingOn: 'Waiting on — late costs', waitingNote: 'These belong to this month even if paid next month (accrual). The month stays Provisional until they land.',
    finalTitle: 'Month closed', finalBody: 'Reconciled and locked. Late costs all landed in their accrual month. Reopening requires the owner and is audit-logged.',
    twoPnls: 'Two P&Ls — hard access rule', twoPnlsBody: 'The operational P&L (B8) stays with the cost controller: food, waste, variance — no salaries, no rent, no real net. THIS financial P&L is owner-only; the cost controller sees it only through a time-boxed grant (Access tab).',
    accrualNote: 'Accrual-based: every cost counts against the month it belongs to, not the month it was paid. Revenue categories from POS day-close; COGS from the operational P&L; expenses from ACC-EXP-01.',
    stmtFoot: 'Click any line to drill to its source (sales, expenses, payroll). Combined nets transfers at cost — no double count.',
    grantTitle: 'Grant temporary access', grantBody: 'Owner-only. Opens the financial P&L to the cost controller for month-end reconciliation. Not a role — a window you open and close.',
    grantee: 'Marc', granteeRole: 'Cost controller', scopeMonth: 'Scope — month', window: 'Access window',
    winRecon: 'Until reconciliation ends', win7: '7 days', win48: '48 hours',
    grantWarn: 'Auto-expires at the window end. Every grant AND every access under it is audit-logged (E4).',
    grantCta: 'Grant time-boxed access', activeGrants: 'Active grants', activeSt: 'Active', revoke: 'Revoke early',
    noActive: 'No active grants — the financial P&L is owner-only right now.',
    grantHistory: 'Grant history', accessFoot: 'Grants never outlive their window. Revoking early is immediate and logged.',
    cancel: 'Cancel',
    finalModalT: 'Mark this month Final?', finalModalB: 'Confirms all late costs for the month have landed and reconciled. The month locks; the accountant export becomes the closing version.',
    finalModalW: 'Locked months reopen only by the owner — reopening is audit-logged.', finalModalCta: 'Reconcile & lock',
    grantToast: 'Access granted — expires automatically', revokeToast: 'Grant revoked — access closed now',
    finalToast: 'Month locked — closing export ready', exportToast: 'Export queued — accountant handoff', drillToast: 'Opening source —',
    locs: { all: 'Combined', rock: 'Rock', kad: 'Kaddoum', mk: 'Main Kitchen' },
    // ── keys added for the store-backed port ──
    lines: {
      revenueByCat: 'Revenue by category', food: 'Food', beverage: 'Beverage', tobacco: 'Tobacco', taxCollected: 'Tax collected',
      cogs: 'COGS (food) — from operational P&L', grossMargin: 'Gross margin', opex: 'Operating expenses',
      salaries: 'Salaries', rent: 'Rent', utilities: 'Utilities (elec · gas)', marketing: 'Marketing', maintenance: 'Maintenance', uniforms: 'Uniforms', taxPaid: 'Tax paid', other: 'Other', netProfit: 'Net profit',
    },
    split3: '(÷3)',
    waitSalaries: 'Salaries — {m}', waitSalariesSub: 'payroll runs 02 {m}',
    waitRent: 'Rent — {locs}', waitRentSub: 'usually paid 05 {m}',
    waitElec: 'Electricity — generator', waitElecSub: 'bill lands ~08 {m}',
    perLine: 'per line', payroll: 'payroll (HR-PAY-01)',
    autoExpires: 'auto-expires', expiresOn: 'expires', autoExpired: 'auto-expired', revokedEarly: 'revoked early', endedOnFinal: 'ended — month marked Final',
    histWhat: '{who} · {m} reconciliation (scope: {m})', histWhatWin: '{who} · {win} ({m})',
    granteeLabel: 'Grantee',
    lockedTitle: 'Owner-only', lockedBody: 'The financial P&L is walled off by default. Ask the owner for a time-boxed grant covering this month to view it.',
    accessAudit: 'Financial P&L viewed under grant',
  },
  ar: {
    pnlTab: 'الأرباح والخسائر المالية', accessTab: 'منح الوصول', ownerOnly: 'للمالك فقط',
    value: 'القيمة', pctOfSales: '٪ من المبيعات', exportAcct: 'تصدير للمحاسب',
    provisional: 'مؤقت', finalSt: 'نهائي · مقفل',
    provText: 'الأرقام التشغيلية مكتملة، لكن التكاليف المتأخرة التي تخص هذا الشهر ما زالت معلقة. يبقى الشهر مفتوحاً حتى تصل.',
    finalText: 'وصلت كل التكاليف المتأخرة وسُوّيت. الشهر مقفل — مكتمل الاستحقاق.',
    markFinal: 'تسوية وإقفال نهائي…', pendingChip: 'معلّق',
    waitingOn: 'بانتظار — تكاليف متأخرة', waitingNote: 'تخص هذا الشهر حتى لو دُفعت الشهر التالي (استحقاق). يبقى الشهر مؤقتاً حتى تصل.',
    finalTitle: 'الشهر مقفل', finalBody: 'سُوّي وأُقفل. وصلت كل التكاليف المتأخرة في شهر استحقاقها. إعادة الفتح تتطلب المالك وتُسجل بالتدقيق.',
    twoPnls: 'قائمتا أرباح وخسائر — قاعدة وصول صارمة', twoPnlsBody: 'القائمة التشغيلية (B8) تبقى لمراقب الكلفة: طعام وهدر وفروقات — بلا رواتب أو إيجار أو صافي حقيقي. هذه القائمة المالية للمالك فقط؛ يراها مراقب الكلفة عبر منحة مؤقتة فقط (تبويب الوصول).',
    accrualNote: 'على أساس الاستحقاق: كل تكلفة تُحسب على الشهر الذي تخصه لا شهر دفعها. فئات الإيراد من إقفال POS؛ كلفة البضاعة من القائمة التشغيلية؛ المصاريف من ACC-EXP-01.',
    stmtFoot: 'انقر أي بند للوصول إلى مصدره (مبيعات، مصاريف، رواتب). المجمّع يصفّي التحويلات بالكلفة — بلا ازدواج.',
    grantTitle: 'منح وصول مؤقت', grantBody: 'للمالك فقط. يفتح القائمة المالية لمراقب الكلفة لتسوية نهاية الشهر. ليست صلاحية — نافذة تفتحها وتغلقها.',
    grantee: 'مارك', granteeRole: 'مراقب الكلفة', scopeMonth: 'النطاق — الشهر', window: 'نافذة الوصول',
    winRecon: 'حتى انتهاء التسوية', win7: '٧ أيام', win48: '٤٨ ساعة',
    grantWarn: 'تنتهي تلقائياً بنهاية النافذة. كل منحة وكل وصول ضمنها يُسجل بالتدقيق (E4).',
    grantCta: 'منح وصول محدد المدة', activeGrants: 'المنح الفعالة', activeSt: 'فعالة', revoke: 'إلغاء مبكر',
    noActive: 'لا منح فعالة — القائمة المالية للمالك فقط الآن.',
    grantHistory: 'سجل المنح', accessFoot: 'المنح لا تتجاوز نافذتها أبداً. الإلغاء المبكر فوري ويُسجل.',
    cancel: 'إلغاء',
    finalModalT: 'إقفال هذا الشهر نهائياً؟', finalModalB: 'يؤكد وصول كل التكاليف المتأخرة وتسويتها. يُقفل الشهر ويصبح تصدير المحاسب النسخة الختامية.',
    finalModalW: 'الأشهر المقفلة يعيد فتحها المالك فقط — ويُسجل ذلك بالتدقيق.', finalModalCta: 'تسوية وإقفال',
    grantToast: 'مُنح الوصول — ينتهي تلقائياً', revokeToast: 'أُلغيت المنحة — أُغلق الوصول الآن',
    finalToast: 'أُقفل الشهر — تصدير الإقفال جاهز', exportToast: 'التصدير في الطابور — تسليم المحاسب', drillToast: 'فتح المصدر —',
    locs: { all: 'مجمّع', rock: 'روك', kad: 'قدّوم', mk: 'المطبخ الرئيسي' },
    // ── keys added for the store-backed port ──
    lines: {
      revenueByCat: 'الإيرادات حسب الفئة', food: 'طعام', beverage: 'مشروبات', tobacco: 'تبغ', taxCollected: 'ضريبة محصلة',
      cogs: 'كلفة البضاعة (طعام) — من التشغيلية', grossMargin: 'الهامش الإجمالي', opex: 'مصاريف التشغيل',
      salaries: 'رواتب', rent: 'إيجار', utilities: 'مرافق (كهرباء · غاز)', marketing: 'تسويق', maintenance: 'صيانة', uniforms: 'زي موحد', taxPaid: 'ضريبة مدفوعة', other: 'أخرى', netProfit: 'صافي الربح',
    },
    split3: '(÷٣)',
    waitSalaries: 'رواتب — {m}', waitSalariesSub: 'كشف الرواتب في ٢ {m}',
    waitRent: 'إيجار — {locs}', waitRentSub: 'يُدفع عادة في ٥ {m}',
    waitElec: 'كهرباء — مولد', waitElecSub: 'تصل الفاتورة ~٨ {m}',
    perLine: 'حسب البند', payroll: 'الرواتب (HR-PAY-01)',
    autoExpires: 'ينتهي تلقائياً', expiresOn: 'ينتهي', autoExpired: 'انتهت تلقائياً', revokedEarly: 'أُلغيت مبكراً', endedOnFinal: 'انتهت — أُقفل الشهر نهائياً',
    histWhat: '{who} · تسوية {m} (نطاق: {m})', histWhatWin: '{who} · {win} ({m})',
    granteeLabel: 'المستفيد',
    lockedTitle: 'للمالك فقط', lockedBody: 'القائمة المالية محجوبة افتراضياً. اطلب من المالك منحة محددة المدة تغطي هذا الشهر لعرضها.',
    accessAudit: 'عرض القائمة المالية ضمن منحة',
  },
};

export type PnlText = typeof TEXT.en;
