/** TEXT dictionary — copied verbatim from "KIS Items & UOM.dc.html". */
const en = {
  items: 'Items', allLocations: 'All locations', totalItems: 'Total items', byType: 'By type', dataHealth: 'Data health',
  missingConv: 'missing base unit / conversion', searchPh: 'Search code, name, supplier…', newItem: 'New item',
  code: 'Code', name: 'Name', type: 'Type', category: 'Category', base: 'Base', purchase: 'Purchase', cost: 'Cost',
  price: 'Price', supplier: 'Supplier', flagsCol: 'Flags', incomplete: 'Incomplete', emptyList: 'No items match — adjust search or filters.',
  movingAvg: 'Moving-avg cost / base unit', unitRoles: 'Unit roles per stage', conversions: 'Conversion builder',
  addConversion: 'Add conversion', convRule: 'Rule', resolved: 'Resolved to base', effective: 'Effective', edit: 'Edit',
  liveResolution: 'Live resolution to base', stockExample: 'Worked stock example', costIllustration: 'Cost illustration',
  versionNote: 'Conversions are versioned. Changing a factor applies forward only — historical transactions keep the factor active at their time.',
  editFactor: 'Edit conversion factor', factorWarning: 'Applies from today. Past transactions keep their original conversion — history is never restated.',
  applyToday: 'Apply from today', cancel: 'Cancel', auditNote: 'Every edit on this item is written to the audit log.',
  lastReceipt: 'Last receipt', date: 'Date', event: 'Event', receiptCost: 'Receipt cost', newAvg: 'New moving avg',
  costingNote: 'Read-mostly — moving average is driven by receiving. Both the entered unit and the stored base value are preserved on every transaction.',
  stocked: 'Stocked', minMax: 'Min / Max', shelfLife: 'Shelf life', countFreq: 'Count frequency per location',
  countUnitLbl: 'Count unit', critical: 'Critical', recipeLink: 'Recipe lives in the Recipe builder',
  recipeLinkBody: 'This item is a recipe output. Its ingredients, yield, and built-up cost are defined once in the Recipe module — no duplicate editor here.',
  openBuilder: 'Open in Recipe builder', sellingPrice: 'Selling price', posMapping: 'POS item mapping',
  tabs: { general: 'General', units: 'Units & Conversions', costing: 'Costing', inv: 'Inventory settings', recipe: 'Recipe', pos: 'POS settings' },
  types: { raw: 'Raw material', sub: 'Sub-recipe', prep: 'Prepared', menu: 'Menu item', pack: 'Packaging' },
  roles: { base: 'Base (inventory)', purchasing: 'Purchasing', storage: 'Storage', recipe: 'Recipe', transfer: 'Transfer', count: 'Count', serving: 'Serving', report: 'Report' },
  auto: 'auto', noPath: 'no path to base', fixed: 'FIXED', density: 'DENSITY', inverseAuto: 'inverse auto-derived',
  chained: 'chained', direct: 'direct', all: 'All',
  general: { codeL: 'Code / SKU', nameEn: 'Name (EN)', nameAr: 'Name (AR)', typeL: 'Type', active: 'Active', barcode: 'Barcode / QR', catL: 'Category', supL: 'Primary supplier' },
  freqs: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' }, yes: 'Yes', no: 'No', mapped: 'Mapped',
  // form strings (inline in the prototype's renderVals)
  formNewItem: 'New item', formAddConv: 'Add conversion — ',
  formSubItem: 'Quick form — full details are completed on the item page.',
  formSubConv: 'Fixed rule: 1 unit = factor × another unit.',
  fp1Item: 'Name (EN) — e.g. Halloumi slices', fp1Conv: 'From unit — e.g. BOX',
  fp2Item: 'Name (AR) — e.g. شرائح حلوم', fp2Conv: 'Factor — e.g. 10',
  fp3Item: 'Base unit — e.g. KG', fp3Conv: 'To unit — e.g. KG',
  formWarnItem: 'Created flagged Incomplete until conversions and costing are added. Audit-logged.',
  formWarnConv: 'Applies from today only — past transactions keep their conversion.',
  ctaItem: 'Create item', ctaConv: 'Add conversion',
  toastItem: 'Item created — Incomplete until conversions are added',
  toastConv: 'Conversion added — effective today',
  toastFactor: 'Factor updated — applies from today',
  convWarnA: ' has no conversion path to base ', convWarnB: ' — cost and stock for this item are unreliable until one is added.',
};

export type ItemsText = typeof en;

const ar: ItemsText = {
  items: 'الأصناف', allLocations: 'كل المواقع', totalItems: 'إجمالي الأصناف', byType: 'حسب النوع', dataHealth: 'سلامة البيانات',
  missingConv: 'بدون وحدة أساس / تحويل', searchPh: 'ابحث بالرمز أو الاسم أو المورد…', newItem: 'صنف جديد',
  code: 'الرمز', name: 'الاسم', type: 'النوع', category: 'الفئة', base: 'الأساس', purchase: 'الشراء', cost: 'الكلفة',
  price: 'السعر', supplier: 'المورد', flagsCol: 'مؤشرات', incomplete: 'غير مكتمل', emptyList: 'لا توجد أصناف مطابقة — عدّل البحث أو الفلاتر.',
  movingAvg: 'متوسط الكلفة المتحرك / وحدة الأساس', unitRoles: 'أدوار الوحدات لكل مرحلة', conversions: 'بناء التحويلات',
  addConversion: 'إضافة تحويل', convRule: 'القاعدة', resolved: 'محلولة إلى الأساس', effective: 'سارية من', edit: 'تعديل',
  liveResolution: 'التحليل الفوري إلى الأساس', stockExample: 'مثال مخزون عملي', costIllustration: 'توضيح الكلفة',
  versionNote: 'التحويلات مؤرشفة بإصدارات. تغيير المعامل يسري مستقبلاً فقط — المعاملات التاريخية تحتفظ بمعاملها وقتها.',
  editFactor: 'تعديل معامل التحويل', factorWarning: 'يسري من اليوم. المعاملات السابقة تحتفظ بتحويلها الأصلي — لا يُعاد تعديل التاريخ أبداً.',
  applyToday: 'تطبيق من اليوم', cancel: 'إلغاء', auditNote: 'كل تعديل على هذا الصنف يُسجل في سجل التدقيق.',
  lastReceipt: 'آخر استلام', date: 'التاريخ', event: 'الحدث', receiptCost: 'كلفة الاستلام', newAvg: 'المتوسط الجديد',
  costingNote: 'للقراءة غالباً — المتوسط المتحرك يتحدد من الاستلام. تُحفظ الوحدة المدخلة وقيمة الأساس معاً في كل معاملة.',
  stocked: 'مخزّن', minMax: 'الحد الأدنى / الأقصى', shelfLife: 'مدة الصلاحية', countFreq: 'تواتر الجرد لكل موقع',
  countUnitLbl: 'وحدة العد', critical: 'حرج', recipeLink: 'الوصفة في منشئ الوصفات',
  recipeLinkBody: 'هذا الصنف ناتج وصفة. مكوناته وإنتاجيته وكلفته المتراكمة تُعرّف مرة واحدة في وحدة الوصفات — لا محرر مكرر هنا.',
  openBuilder: 'فتح في منشئ الوصفات', sellingPrice: 'سعر البيع', posMapping: 'ربط صنف نقاط البيع',
  tabs: { general: 'عام', units: 'الوحدات والتحويلات', costing: 'التكلفة', inv: 'إعدادات المخزون', recipe: 'الوصفة', pos: 'إعدادات POS' },
  types: { raw: 'مادة خام', sub: 'وصفة فرعية', prep: 'مُحضّر', menu: 'صنف قائمة', pack: 'تغليف' },
  roles: { base: 'الأساس (المخزون)', purchasing: 'الشراء', storage: 'التخزين', recipe: 'الوصفة', transfer: 'التحويل', count: 'العد', serving: 'التقديم', report: 'التقارير' },
  auto: 'تلقائي', noPath: 'لا مسار إلى الأساس', fixed: 'ثابت', density: 'كثافة', inverseAuto: 'المعكوس مشتق تلقائياً',
  chained: 'متسلسل', direct: 'مباشر', all: 'الكل',
  general: { codeL: 'الرمز / SKU', nameEn: 'الاسم (EN)', nameAr: 'الاسم (AR)', typeL: 'النوع', active: 'فعّال', barcode: 'باركود / QR', catL: 'الفئة', supL: 'المورد الرئيسي' },
  freqs: { daily: 'يومي', weekly: 'أسبوعي', monthly: 'شهري' }, yes: 'نعم', no: 'لا', mapped: 'مربوط',
  formNewItem: 'صنف جديد', formAddConv: 'إضافة تحويل — ',
  formSubItem: 'نموذج سريع — التفاصيل الكاملة تُستكمل في صفحة الصنف.',
  formSubConv: 'قاعدة ثابتة: 1 وحدة = معامل × وحدة أخرى.',
  fp1Item: 'الاسم (EN) — مثال: Halloumi slices', fp1Conv: 'من وحدة — مثال: BOX',
  fp2Item: 'الاسم (عربي) — مثال: شرائح حلوم', fp2Conv: 'المعامل — مثال: 10',
  fp3Item: 'وحدة الأساس — مثال: KG', fp3Conv: 'إلى وحدة — مثال: KG',
  formWarnItem: 'يُنشأ بعلامة «غير مكتمل» حتى تُضاف التحويلات والتكلفة. يُسجل بالتدقيق.',
  formWarnConv: 'يسري من اليوم فقط — المعاملات السابقة تحتفظ بتحويلها.',
  ctaItem: 'إنشاء الصنف', ctaConv: 'إضافة التحويل',
  toastItem: 'أُنشئ الصنف — غير مكتمل حتى تُضاف التحويلات',
  toastConv: 'أُضيف التحويل — يسري من اليوم',
  toastFactor: 'حُدّث المعامل — يسري من اليوم',
  convWarnA: ' لا يملك مسار تحويل إلى الأساس ', convWarnB: ' — الكلفة والمخزون لهذا الصنف غير موثوقين حتى يُضاف.',
};

export const TEXT = { en, ar };
