/** MGT-PRD-01 / MGT-PRD-05 — TEXT dictionary (prototype strings verbatim + a few keys the store integration needs). */
const EN = {
  title: 'Production',
  planning: 'Production planning', monitoring: 'Monitoring & yield',
  planHint: 'Plan lines are informed by historical sales, expected demand, and current stock. Publishing pushes tasks to staff tablets.',
  addLine: 'Add line', publish: 'Publish plan', published: 'Published ✓',
  product: 'Product', demandHint: 'Expected demand', stock: 'Stock', plannedQty: 'Planned', assignTo: 'Assign to', flag: 'Flag',
  planNote: 'Overproduction vs expected demand is flagged amber before publishing. The plan feeds each staff member’s Today list.',
  batchesToday: 'Batches today', avgYield: 'Avg yield vs standard', yieldFlags: 'Yield flags', overproduction: 'Overproduction',
  liveBoard: 'Live batch board', approve: 'Approve production', approvedLbl: 'Approved ✓', fullTrace: 'Full trace',
  investigateYield: 'Investigate yield',
  yieldPanel: 'Yield vs standard · this week', yieldNote: 'Black tick = standard. Flag the problem, never auto-blame the person.',
  overPanel: 'Overproduction vs expected demand',
  publishToast: 'Plan published — tasks on staff tablets', approveToast: 'Batch approved — output posted to stock',
  traceToast: 'Opening full batch trace —', invToast: 'Yield investigation opened —',
  st: { planned: 'Planned', progress: 'In progress', pending: 'Awaiting approval', done: 'Completed' },
  staff: ['Rami', 'Layal', 'Karim'],
  locs: { mk: 'Main Kitchen', rock: 'Rock', kad: 'Kaddoum' },
  // ── additions for the store-backed port ──
  date: '12 Aug 2026', demandBasis: 'Wed avg, 8w', perDay: '/ day', vs: 'vs', needWord: 'need', unassigned: 'Unassigned',
  alreadyPublished: 'Plan already published — edit a line to republish', pickProduct: 'Pick a product — demo',
  addLineTitle: 'Add plan line', addLineSub: 'The new line stays unpublished until you publish the plan.', location: 'Location', qty: 'Quantity', add: 'Add line', cancel: 'Cancel',
  noProducts: 'All recipe products are already on today’s plan.', noPlans: 'No plan lines for this location today.', noBatches: 'No batches on the board for this location.', noOver: 'Nothing over expected demand.', noYield: 'No completed batches this week for this location.',
  confirmApprove: 'Approve production?', confirmApproveBody: 'The batch output will be posted to stock. This can’t be undone.',
  pt: 'pt', stageWord: 'stage', unit: 'Unit', draft: 'draft',
  d: {
    batchDetail: 'Batch detail', employee: 'Employee', started: 'Started', completed: 'Completed', inputMode: 'Input mode', commit: 'Commit exact', draw: 'Draw & return',
    rawDrawn: 'Raw drawn', rawReturned: 'Leftover returned', rawUsed: 'Actual used', trimWaste: 'Trimming waste', marRec: 'Marinade (recipe)', marUsed: 'Marinade (used)',
    stdWeight: 'Recipe standard', gap: 'Gap (w · % · $)', gapStatus: 'Gap status', gapOpen: 'Open', gapAccepted: 'Accepted', gapFlagged: 'Flagged',
    cost: 'Built-up cost', yield: 'Yield', movements: 'Stock movements', noMovements: 'No movements posted yet.', close: 'Close', outputQty: 'Output', planned: 'Planned', plan: 'Plan', progress: 'Progress',
    mv: { production_out: 'Production out', production_in: 'Production in', waste: 'Waste' } as Record<string, string>,
  },
};

export type Text = typeof EN;

export const TEXT: Record<'en' | 'ar', Text> = {
  en: EN,
  ar: {
    title: 'الإنتاج',
    planning: 'تخطيط الإنتاج', monitoring: 'المراقبة والإنتاجية',
    planHint: 'أسطر الخطة تسترشد بالمبيعات التاريخية والطلب المتوقع والمخزون الحالي. النشر يرسل المهام إلى أجهزة الموظفين.',
    addLine: 'إضافة سطر', publish: 'نشر الخطة', published: 'نُشرت ✓',
    product: 'الصنف', demandHint: 'الطلب المتوقع', stock: 'المخزون', plannedQty: 'المخطط', assignTo: 'إسناد إلى', flag: 'مؤشر',
    planNote: 'الإنتاج الزائد عن الطلب المتوقع يُعلَّم كهرمانياً قبل النشر. الخطة تغذي قائمة مهام كل موظف.',
    batchesToday: 'دفعات اليوم', avgYield: 'متوسط الإنتاجية مقابل المعيار', yieldFlags: 'إشارات الإنتاجية', overproduction: 'إنتاج زائد',
    liveBoard: 'لوحة الدفعات المباشرة', approve: 'اعتماد الإنتاج', approvedLbl: 'معتمد ✓', fullTrace: 'التتبع الكامل',
    investigateYield: 'تحقيق في الإنتاجية',
    yieldPanel: 'الإنتاجية مقابل المعيار · هذا الأسبوع', yieldNote: 'العلامة السوداء = المعيار. علّم المشكلة، لا تلم الشخص تلقائياً.',
    overPanel: 'الإنتاج الزائد مقابل الطلب المتوقع',
    publishToast: 'نُشرت الخطة — المهام على أجهزة الموظفين', approveToast: 'اعتُمدت الدفعة — رُحّل الناتج للمخزون',
    traceToast: 'فتح تتبع الدفعة الكامل —', invToast: 'فُتح تحقيق الإنتاجية —',
    st: { planned: 'مخطط', progress: 'قيد التنفيذ', pending: 'بانتظار الاعتماد', done: 'مكتمل' },
    staff: ['رامي', 'ليال', 'كريم'],
    locs: { mk: 'المطبخ الرئيسي', rock: 'روك', kad: 'قدّوم' },
    date: '١٢ آب ٢٠٢٦', demandBasis: 'متوسط الأربعاء، ٨ أسابيع', perDay: '/ يوم', vs: 'مقابل', needWord: 'الحاجة', unassigned: 'غير مسند',
    alreadyPublished: 'الخطة منشورة — عدّل سطراً لإعادة النشر', pickProduct: 'اختيار صنف — تجريبي',
    addLineTitle: 'إضافة سطر خطة', addLineSub: 'يبقى السطر الجديد غير منشور حتى تنشر الخطة.', location: 'الموقع', qty: 'الكمية', add: 'إضافة سطر', cancel: 'إلغاء',
    noProducts: 'كل منتجات الوصفات موجودة في خطة اليوم.', noPlans: 'لا أسطر خطة لهذا الموقع اليوم.', noBatches: 'لا دفعات على اللوحة لهذا الموقع.', noOver: 'لا شيء يتجاوز الطلب المتوقع.', noYield: 'لا دفعات مكتملة هذا الأسبوع لهذا الموقع.',
    confirmApprove: 'اعتماد الإنتاج؟', confirmApproveBody: 'سيُرحَّل ناتج الدفعة إلى المخزون. لا يمكن التراجع عن هذا الإجراء.',
    pt: 'نقطة', stageWord: 'مرحلة', unit: 'الوحدة', draft: 'مسودة',
    d: {
      batchDetail: 'تفاصيل الدفعة', employee: 'الموظف', started: 'بدأت', completed: 'اكتملت', inputMode: 'طريقة الإدخال', commit: 'التزام دقيق', draw: 'سحب وإرجاع',
      rawDrawn: 'الخام المسحوب', rawReturned: 'المتبقي المعاد', rawUsed: 'المستخدم فعلاً', trimWaste: 'هدر التشفية', marRec: 'التتبيلة (وصفة)', marUsed: 'التتبيلة (مستخدم)',
      stdWeight: 'معيار الوصفة', gap: 'الفجوة (وزن · ٪ · $)', gapStatus: 'حالة الفجوة', gapOpen: 'مفتوحة', gapAccepted: 'مقبولة', gapFlagged: 'مُبلّغة',
      cost: 'الكلفة المتراكمة', yield: 'الإنتاجية', movements: 'حركات المخزون', noMovements: 'لم تُرحّل حركات بعد.', close: 'إغلاق', outputQty: 'الناتج', planned: 'المخطط', plan: 'الخطة', progress: 'التقدم',
      mv: { production_out: 'صرف إنتاج', production_in: 'إدخال إنتاج', waste: 'هدر' },
    },
  },
};
